#!/usr/bin/env bash
# template-task: 2.0.0
#######################################
# AWS Cognito / Password / Reset
#
# Version: 1.1.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/aws-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Functions
#

function initialize() {
  bl64_dbg_app_show_function
  s64_aws_lib_setup
}

#
# Main
#

declare COGNITO_POOL_ID="${1:-}"
declare COGNITO_USERNAME="${2:-}"
declare COGNITO_PASSWORD="${3:-}"

bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_aws_run_aws \
  cognito-idp \
  admin-set-user-COGNITO_PASSWORD \
  --user-pool-id "$COGNITO_POOL_ID" \
  --username "$COGNITO_USERNAME" \
  --password "$COGNITO_PASSWORD"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
