#!/usr/bin/env bash
# template-task: 3.0.0
#   template-task-base: 2.0.0
#######################################
# Copyright [SerDigital64 - https://github.com/serdigital64]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/X_MODULE_X-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# X_GLOBALS_PLACEHOLDER_X

#
# Functions
#

function X_COMMAND_X() {
  bl64_dbg_app_show_function "$@"
  # X_COMMAND_PLACEHOLDER_X
}

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'COMMAND' || { help && return 1; }
  s64_X_MODULE_X_lib_setup
  # X_INIT_PLACEHOLDER_X
}

function help() {
  bl64_msg_show_usage \
    '-x [-V Verbose] [-D Debug] [-h]' \
    'X_MODULE_NAME_X / [X_SUBMODULE_NAME_X /] X_APP_NAME_X' \
    '
    -x         : X_COMMAND_INFO_X
    ' '
    -h         : Show help
    ' '
    -V Verbose : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
    -D Debug   : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
    '
}

#
# Main
#

declare COMMAND="$BL64_VAR_NULL"
declare OPTION=''

(($# == 0)) && help && exit 1
while getopts ':xV:D:h' OPTION; do
  case "$OPTION" in
  x) COMMAND='X_COMMAND_X' ;;
  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
  h) help && exit 0 ;;
  *) help && exit 1 ;;
  esac
done
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?

bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$COMMAND"
"${COMMAND}"
bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$COMMAND"
