#!/usr/bin/env bash
# template: 1.0.0
#######################################
# PGSQL / Lib
#
# Version: 1.1.1
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

declare SYSOP64_PGSQL_SERVER_LAB_NAME="${SYSOP64_PGSQL_SERVER_LAB_NAME:-pgsql-lab}"
declare SYSOP64_PGSQL_SERVER_LAB_PASSWORD="${SYSOP64_PGSQL_SERVER_LAB_PASSWORD:-Random-Password.${RANDOM}}"
declare SYSOP64_PGSQL_PATH_CLI="${SYSOP64_PGSQL_PATH_CLI:-}"

declare SYSOP64_PGSQL_SERVER_HOST="${SYSOP64_PGSQL_SERVER_HOST:-localhost}"
declare SYSOP64_PGSQL_SERVER_USER="${SYSOP64_PGSQL_SERVER_USER:-postgres}"
declare SYSOP64_PGSQL_SERVER_PORT="${SYSOP64_PGSQL_SERVER_PORT:-5432}"
declare SYSOP64_PGSQL_SERVER_PASSWORD="${SYSOP64_PGSQL_SERVER_PASSWORD:-}"
declare SYSOP64_PGSQL_DB_NAME="${SYSOP64_PGSQL_DB_NAME:-postgres}"

function psql_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$SYSOP64_PGSQL_PATH_CLI" ]]; then
    if [[ -x '/home/linuxbrew/.linuxbrew/bin/psql' ]]; then
      SYSOP64_PGSQL_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/psql'
    elif [[ -x '/opt/homebrew/bin/psql' ]]; then
      SYSOP64_PGSQL_PATH_CLI='/opt/homebrew/bin/psql'
    elif [[ -x '/usr/local/bin/psql' ]]; then
      SYSOP64_PGSQL_PATH_CLI='/usr/local/bin/psql'
    elif [[ -x '/usr/bin/psql' ]]; then
      SYSOP64_PGSQL_PATH_CLI='/usr/bin/psql'
    else
      bl64_check_alert_resource_not_found 'psql'
      return $?
    fi
  else
    bl64_check_command "$SYSOP64_PGSQL_PATH_CLI"
  fi
}

function psql_lib_run_psql() {
  bl64_dbg_app_show_function "$@"
  "$SYSOP64_PGSQL_PATH_CLI" \
    "$@"
}
