#!/usr/bin/env bash
# Template: 1.0.0
#######################################
# PGSQL / Lib
#
# Version: 1.1.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

#
# Globals
#

declare SYSOP64_PGSQL_SERVER_LAB_NAME="${SYSOP64_PGSQL_SERVER_LAB_NAME:-pgsql-lab}"
declare SYSOP64_PGSQL_SERVER_LAB_PASSWORD="${SYSOP64_PGSQL_SERVER_LAB_PASSWORD:-Random-Password.${RANDOM}}"
declare SYSOP64_PGSQL_CLI_PATH="${SYSOP64_PGSQL_CLI_PATH:-/usr/bin/psql}"

declare SYSOP64_PGSQL_SERVER_HOST="${SYSOP64_PGSQL_SERVER_HOST:-localhost}"
declare SYSOP64_PGSQL_SERVER_USER="${SYSOP64_PGSQL_SERVER_USER:-postgres}"
declare SYSOP64_PGSQL_SERVER_PORT="${SYSOP64_PGSQL_SERVER_PORT:-5432}"
declare SYSOP64_PGSQL_SERVER_PASSWORD="${SYSOP64_PGSQL_SERVER_PASSWORD:-}"
declare SYSOP64_PGSQL_DB_NAME="${SYSOP64_PGSQL_DB_NAME:-postgres}"
