#!/usr/bin/env bash
# template-task-base: 2.3.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/pgsql.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

declare MY_COMMAND="$BL64_VAR_NULL"
declare MY_OPTION=''

function start() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'start Postgresql Server in container mode'
  bl64_cnt_run \
    --name "$S64_PGSQL_LAB_NAME" \
    --env POSTGRES_PASSWORD="$S64_PGSQL_LAB_PASSWORD" \
    --detach \
    --publish "$S64_PGSQL_LAB_PORT:$S64_PGSQL_LAB_PORT" \
    "$S64_PGSQL_LAB_CONTAINER"
}

function stop() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'stop Postgresql Server running in container mode'
  bl64_cnt_cli \
    stop \
    "$S64_PGSQL_LAB_NAME" &&
    bl64_cnt_cli \
      rm \
      "$S64_PGSQL_LAB_NAME"
}

function my_initialize() {
  bl64_dbg_app_show_function
  [[ -n "$MY_OPTION" && -n "$MY_COMMAND" ]] || { bl64_msg_help_show && return 1; }
  bl64_cnt_check_not_in_container &&
    bl64_cnt_setup &&
    bl64_msg_show_setup 'BL64_VAR_DEFAULT' \
      'S64_PGSQL_LAB_CONTAINER' \
      'S64_PGSQL_LAB_NAME' \
      'S64_PGSQL_LAB_PASSWORD' \
      'S64_PGSQL_LAB_PORT'
}

bl64_lib_script_version_set '2.0.3'
bl64_msg_help_usage_set '-s|-o [-V Verbose] [-D Debug] [-h]'
bl64_msg_help_about_set 'Control PostgreSQL lab container'
bl64_msg_help_parameters_set \
  '-s         : Start container and detach
-o         : Stop detached container
-h         : Show help
-V Verbose : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
-D Debug   : Enable debugging mode. Format: one of BL64_DBG_TARGET_*'

(($# == 0)) && bl64_msg_help_show && exit 1
while getopts ':soV:D:h' MY_OPTION; do
  case "$MY_OPTION" in
    s) MY_COMMAND='start' ;;
    o) MY_COMMAND='stop' ;;
    V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
    D) S64_CORE_SET_DEBUG="$OPTARG" ;;
    h) bl64_msg_help_show && exit 0 ;;
    *) bl64_msg_help_show && exit 1 ;;
  esac
done
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && s64_core_lib_set_verbose && my_initialize || exit $?

bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$MY_COMMAND"
"${MY_COMMAND}"
bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$MY_COMMAND"
