#!/usr/bin/env bash
# template-task: 2.0.0
#######################################
# PGSQL / Server / Lab / Control
#
# Version: 1.0.2
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/pgsql-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Functions
#

function start() {
  bl64_dbg_app_show_function
  local container_port='5432'
  bl64_msg_show_task 'start Postgresql Server in container mode'
  bl64_cnt_run \
    --name "$S64_PGSQL_SERVER_LAB_NAME" \
    --env POSTGRES_PASSWORD="$S64_PGSQL_SERVER_LAB_PASSWORD" \
    --detach \
    --publish "$container_port:$container_port" \
    postgres &&
    bl64_msg_show_info "Starded container information
Container Name: ${S64_PGSQL_SERVER_LAB_NAME}
Password: ${S64_PGSQL_SERVER_LAB_PASSWORD}
Port: ${container_port}"
}

function stop() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'stop Postgresql Server running in container mode'
  bl64_cnt_cli \
    stop \
    "$S64_PGSQL_SERVER_LAB_NAME" &&
    bl64_cnt_cli \
      rm \
      "$S64_PGSQL_SERVER_LAB_NAME"
}

function initialize() {
  bl64_dbg_app_show_function

  bl64_check_parameter 'COMMAND' ||
    { help && return 1; }

  bl64_cnt_check_not_in_container &&
    bl64_cnt_setup
}

function help() {
  bl64_msg_show_usage \
    '-s|-o [-V Verbose] [-D Debug] [-h]' \
    'PGSQL / Server / Lab / Control' \
    '
    -s         : Start container and detach
    -o         : Stop detached container
    ' '
    -h         : Show help
    ' '
    -V Verbose : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
    -D Debug   : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
    '
}

#
# Main
#

declare COMMAND="$BL64_VAR_NULL"
declare OPTION=''

(($# == 0)) && help && exit 1
while getopts ':soV:D:h' OPTION; do
  case "$OPTION" in
  s) COMMAND='start' ;;
  o) COMMAND='stop' ;;
  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
  h) help && exit 0 ;;
  *) help && exit 1 ;;
  esac
done
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?

bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$COMMAND"
"${COMMAND}"
bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$COMMAND"
