#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/airflow.lib" || { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

declare MAIN_HOST_PORT="${1:-$S64_AIRFLOW_LAB_HOST_PORT}"
declare MAIN_CONTAINER_TAG="${2:-$S64_AIRFLOW_LAB_IMAGE_TAG}"

function my_initialize() {
  bl64_dbg_app_show_function
  s64_core_lib_show_about
  s64_airflow_lib_setup &&
    bl64_cnt_setup &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'S64_AIRFLOW_LAB_IMAGE_NAME' \
      'MAIN_HOST_PORT' \
      'MAIN_CONTAINER_TAG'
}

bl64_lib_script_version_set '1.1.0'
bl64_msg_help_about_set 'Run AirFlow Standalone container for local lab testing'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_cnt_run_docker \
  run \
  --rm \
  --tty \
  --interactive \
  --publish "$MAIN_HOST_PORT":"$S64_AIRFLOW_LAB_CONTAINER_PORT" \
  --name "$S64_AIRFLOW_LAB_CONTAINER_NAME" \
  "${S64_AIRFLOW_LAB_IMAGE_NAME}:${MAIN_CONTAINER_TAG}" \
  standalone
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
