#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/linux.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

declare MY_PACKAGE_NAME="${1:-}"

function my_task() {
  bl64_dbg_app_show_function
  case "$BL64_OS_FLAVOR" in
    "$BL64_OS_FLAVOR_ARCH") bl64_pkg_run_pacman --query --info "${MY_PACKAGE_NAME}" ;;
    "$BL64_OS_FLAVOR_DEBIAN") bl64_pkg_run_apt show "${MY_PACKAGE_NAME}" ;;
    "$BL64_OS_FLAVOR_FEDORA" | "$BL64_OS_FLAVOR_REDHAT") bl64_pkg_run_rpm --query --info "${MY_PACKAGE_NAME}" ;;
    "$BL64_OS_FLAVOR_ALPINE") bl64_pkg_run_apk info "${MY_PACKAGE_NAME}" ;;
    *) bl64_check_rise_task_unsupported || return $? ;;
  esac
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_linux_lib_setup &&
    bl64_check_parameter 'MY_PACKAGE_NAME' &&
    s64_core_lib_task_show_setup \
      'MY_PACKAGE_NAME'
}

bl64_lib_script_version_set '1.1.0'
bl64_msg_help_set_about 'Show OS package details'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_task
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
