#!/usr/bin/env bash
# template: 1.0.0
#######################################
# AWS / Lib
#
# Version: 1.1.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

# Access mode credentials
declare SYSOP64_AWS_ACCESS_KEY_ID="${SYSOP64_AWS_ACCESS_KEY_ID:-}"
declare SYSOP64_AWS_ACCESS_KEY_SECRET="${SYSOP64_AWS_ACCESS_KEY_SECRET:-}"
declare SYSOP64_AWS_ACCESS_PROFILE="${SYSOP64_AWS_ACCESS_PROFILE:-}"
declare SYSOP64_AWS_ACCESS_TOKEN="${SYSOP64_AWS_ACCESS_TOKEN:-}"
declare SYSOP64_AWS_ACCESS_REGION="${SYSOP64_AWS_ACCESS_REGION:-}"
declare SYSOP64_AWS_ACCESS_MODE="${SYSOP64_AWS_ACCESS_MODE:-$BL64_AWS_ACCESS_MODE_KEY}"

# API Endpoints
declare SYSOP64_AWS_API_EKS_AMI_AL2023_X86_64_STANDARD='amazon-linux-2023/x86_64/standard'
declare SYSOP64_AWS_API_EKS_AMI_AL2='amazon-linux-2'

#
# Functions
#

function aws_cli_access_check() {
  bl64_dbg_app_show_function "$@"
  if [[ -n "$SYSOP64_AWS_ACCESS_REGION" ]]; then
    bl64_aws_set_region "$SYSOP64_AWS_ACCESS_REGION"
  fi
  if [[ "$SYSOP64_AWS_ACCESS_MODE" == "$BL64_AWS_ACCESS_MODE_PROFILE" ]]; then
    bl64_check_export 'SYSOP64_AWS_ACCESS_PROFILE' &&
      bl64_aws_access_enable_profile "$SYSOP64_AWS_ACCESS_PROFILE"
  elif [[ "$SYSOP64_AWS_ACCESS_MODE" == "$BL64_AWS_ACCESS_MODE_KEY" ]]; then
    bl64_check_export 'SYSOP64_AWS_ACCESS_KEY_ID' &&
      bl64_check_export 'SYSOP64_AWS_ACCESS_KEY_SECRET' &&
      bl64_aws_access_enable_key "$SYSOP64_AWS_ACCESS_KEY_ID" "$SYSOP64_AWS_ACCESS_KEY_SECRET"
  elif [[ "$SYSOP64_AWS_ACCESS_MODE" == "$BL64_AWS_ACCESS_MODE_TOKEN" ]]; then
    bl64_check_export 'SYSOP64_AWS_ACCESS_KEY_ID' &&
      bl64_check_export 'SYSOP64_AWS_ACCESS_KEY_SECRET' &&
      bl64_check_export 'SYSOP64_AWS_ACCESS_TOKEN' &&
      bl64_aws_access_enable_token "$SYSOP64_AWS_ACCESS_KEY_ID" "$SYSOP64_AWS_ACCESS_KEY_SECRET" "$SYSOP64_AWS_ACCESS_TOKEN"
  fi
}
