#!/usr/bin/env bash
# template: 1.1.0
# template-module-setup: 1.1.0
# template-module-cli: 1.1.0
#######################################
# X_MODULE_NAME_X / Lib
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_X_MODULE_CAPS_X_PATH_CLI="${S64_X_MODULE_CAPS_X_PATH_CLI:-X_MODULE_PATH_CLI_X}"
}

#
# Functions
#

function s64_X_MODULE_X_lib_setup() {
  bl64_dbg_app_show_function
  local command='X_MODULE_COMMAND_CLI_X'
  if [[ -z "$S64_X_MODULE_CAPS_X_PATH_CLI" ]]; then
    if [[ -x "/home/linuxbrew/.linuxbrew/bin/${command}" ]]; then
      S64_X_MODULE_CAPS_X_PATH_CLI="/home/linuxbrew/.linuxbrew/bin/${command}"
    elif [[ -x "/opt/homebrew/bin/${command}" ]]; then
      S64_X_MODULE_CAPS_X_PATH_CLI="/opt/homebrew/bin/${command}"
    elif [[ -x "/usr/local/bin/${command}" ]]; then
      S64_X_MODULE_CAPS_X_PATH_CLI="/usr/local/bin/${command}"
    elif [[ -x "/usr/bin/${command}" ]]; then
      S64_X_MODULE_CAPS_X_PATH_CLI="/usr/bin/${command}"
    else
      bl64_check_alert_resource_not_found "$command"
      return $?
    fi
  else
    bl64_check_command "$S64_X_MODULE_CAPS_X_PATH_CLI" ||
      return $?
  fi
}

function s64_X_MODULE_X_lib_run_X_MODULE_CLI_NAME_X() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_X_MODULE_CAPS_X_PATH_CLI" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}
