#!/usr/bin/env bash
# template-module-lib: 2.2.0
#   template-module-base: 2.2.0
#   template-module-setup: 2.0.0
#   template-module-cli: 1.1.0
#   template-module-vars: 1.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_X_MODULE_CAPS_X_VERSION='1.0.0'
  declare S64_X_MODULE_CAPS_X_PATH_CLI="${S64_X_MODULE_CAPS_X_PATH_CLI:-}"
  # X_GLOBALS_PLACEHOLDER_X
}

#
# Functions
#

function s64_X_MODULE_X_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$S64_X_MODULE_CAPS_X_PATH_CLI" ]]; then
    S64_X_MODULE_CAPS_X_PATH_CLI="$(bl64_bsh_command_locate 'X_CLI_COMMAND_X')"
  else
    bl64_check_command "$S64_X_MODULE_CAPS_X_PATH_CLI"
  fi
}

function s64_X_MODULE_X_lib_run_X_CLI_COMMAND_X() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_X_MODULE_CAPS_X_PATH_CLI" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

# X_FUNCTIONS_PLACEHOLDER_X
