#!/usr/bin/env bash
# template: 1.0.0
#######################################
# X_MODULE_NAME_X / Lib
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_X_MODULE_CAPS_X_PATH_CLI="${S64_X_MODULE_CAPS_X_PATH_CLI:-X_MODULE_PATH_CLI_X}"
}

#
# Functions
#

function s64_X_MODULE_X_lib_run_X_MODULE_CLI_NAME_X() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  "$S64_X_MODULE_CAPS_X_PATH_CLI" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_X_MODULE_X_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$S64_X_MODULE_CAPS_X_PATH_CLI" ]]; then
    if [[ -x '/home/linuxbrew/.linuxbrew/bin/X_MODULE_COMMAND_CLI_X' ]]; then
      S64_X_MODULE_CAPS_X_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/X_MODULE_COMMAND_CLI_X'
    elif [[ -x '/opt/homebrew/bin/X_MODULE_COMMAND_CLI_X' ]]; then
      S64_X_MODULE_CAPS_X_PATH_CLI='/opt/homebrew/bin/X_MODULE_COMMAND_CLI_X'
    elif [[ -x '/usr/local/bin/X_MODULE_COMMAND_CLI_X' ]]; then
      S64_X_MODULE_CAPS_X_PATH_CLI='/usr/local/bin/X_MODULE_COMMAND_CLI_X'
    elif [[ -x '/usr/bin/X_MODULE_COMMAND_CLI_X' ]]; then
      S64_X_MODULE_CAPS_X_PATH_CLI='/usr/bin/X_MODULE_COMMAND_CLI_X'
    else
      bl64_check_alert_resource_not_found 'X_MODULE_COMMAND_CLI_X'
      return $?
    fi
  else
    bl64_check_command "$S64_X_MODULE_CAPS_X_PATH_CLI" ||
      return $?
  fi
}
