#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/linux.lib" || { s64_core_lib_check_module_load && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

declare MY_VERSION="${1:-}"

function my_remove_ubuntu() {
  bl64_dbg_app_show_function
  bl64_pkg_run_apt \
    remove \
    --purge \
    "linux-image-${MY_VERSION}-*" \
    "linux-headers-${MY_VERSION}-*" \
    "linux-modules-${MY_VERSION}-*"
}

function my_remove() {
  bl64_dbg_app_show_function
  case "$BL64_OS_DISTRO" in
    ${BL64_OS_UB}-*) my_remove_ubuntu ;;
    *) bl64_check_alert_unsupported ;;
  esac
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_core_lib_show_about
  bl64_check_privilege_root &&
    bl64_check_parameter 'MY_VERSION' &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'MY_VERSION' &&
    bl64_msg_show_warning 'the operation can break the system' &&
    bl64_ui_ask_confirmation 'ensure there is backup and recovery media.'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'Remove specific kernel version packages'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_remove
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
