#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/libvirt.lib" || { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/linux.lib" && source "${S64_CORE_PATH_ROOT}/core/libvirt.lib" || { s64_core_lib_check_module_load && exit 1; }

function my_stop() {
  bl64_dbg_app_show_function
  case "$BL64_OS_FLAVOR" in
    "$BL64_OS_FLAVOR_ARCH" | "$BL64_OS_FLAVOR_DEBIAN" | "$BL64_OS_FLAVOR_FEDORA" | "$BL64_OS_FLAVOR_REDHAT")
      s64_linux_lib_run_systemctl stop \
        "$S64_LIBVIRT_SERVICE_LIBVIRTD" \
        "$S64_LIBVIRT_SOCKET_LIBVIRTD" \
        "$S64_LIBVIRT_SOCKET_LIBVIRTD_RO" \
        "$S64_LIBVIRT_SOCKET_LIBVIRTD_ADMIN"
      ;;
    *) bl64_check_alert_unsupported ;;
  esac
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_core_lib_show_about
  s64_linux_lib_setup &&
    s64_libvirt_lib_setup &&
    bl64_check_privilege_root
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'Stop the LibVirt service'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_stop
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
