#!/usr/bin/env bash
# template: 1.0.1
#######################################
# GitHub / Lib
#
# Version: 1.0.2
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_GITHUB_PATH_CLI="${S64_GITHUB_PATH_CLI:-}"
}

#
# Functions
#

function s64_github_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$S64_GITHUB_PATH_CLI" ]]; then
    if [[ -x '/home/linuxbrew/.linuxbrew/bin/gh' ]]; then
      S64_GITHUB_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/gh'
    elif [[ -x '/opt/homebrew/bin/gh' ]]; then
      S64_GITHUB_PATH_CLI='/opt/homebrew/bin/gh'
    elif [[ -x '/usr/local/bin/gh' ]]; then
      S64_GITHUB_PATH_CLI='/usr/local/bin/gh'
    elif [[ -x '/usr/bin/gh' ]]; then
      S64_GITHUB_PATH_CLI='/usr/bin/gh'
    else
      bl64_check_alert_resource_not_found 'gh'
      return $?
    fi
  else
    bl64_check_command "$S64_GITHUB_PATH_CLI" ||
      return $?
  fi
}

function s64_github_lib_run_gh() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  "$S64_GITHUB_PATH_CLI" \
    "$@"
  bl64_dbg_app_trace_stop
}
