#!/usr/bin/env bash
# template: 1.0.0
#######################################
# GitHub / Lib
#
# Version: 1.0.1
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

declare SYSOP64_GITHUB_PATH_CLI="${SYSOP64_GITHUB_PATH_CLI:-/usr/bin/gh}"

#
# Functions
#

#######################################
# Command wrapper with verbose, debug and common options
#
# * Trust no one. Ignore inherited config and use explicit config
#
# Arguments:
#   $@: arguments are passed as-is to the command
# Outputs:
#   STDOUT: command output
#   STDERR: command stderr
# Returns:
#   0: operation completed ok
#   >0: operation failed
#######################################
function github_lib_cli_run() {
  bl64_dbg_lib_show_function "$@"

  bl64_check_parameters_none "$#" &&
    bl64_check_command "$SYSOP64_GITHUB_PATH_CLI" ||
    return $?

  bl64_dbg_lib_trace_start
  # shellcheck disable=SC2086
  "$SYSOP64_GITHUB_PATH_CLI" \
    "$@"
  bl64_dbg_lib_trace_stop
}
