#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/linux.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

declare MY_VERSION="${1:-}"

function my_remove_ubuntu() {
  bl64_dbg_app_show_function
  bl64_pkg_run_apt \
    remove \
    --purge \
    "linux-image-${MY_VERSION}-*" \
    "linux-headers-${MY_VERSION}-*" \
    "linux-modules-${MY_VERSION}-*"
}

function my_remove_oraclelinux() {
  bl64_dbg_app_show_function
  bl64_pkg_run_dnf \
    remove \
    "kernel-${MY_VERSION}" \
    "kernel-core-${MY_VERSION}" \
    "kernel-modules-${MY_VERSION}" \
    "kernel-modules-core-${MY_VERSION}" \
    "kernel-modules-extra-${MY_VERSION}" \
    "kernel-modules-extra-matched-${MY_VERSION}" \
    "kernel-tools-${MY_VERSION}" \
    "kernel-tools-libs-${MY_VERSION}" \
    "kernel-uek-${MY_VERSION}" \
    "kernel-uek-core-${MY_VERSION}" \
    "kernel-uek-modules-${MY_VERSION}" \
    "kernel-uek-modules-core-${MY_VERSION}" \
    "kernel-uek-modules-extra-netfilter-${MY_VERSION}"
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_linux_lib_setup &&
    bl64_check_privilege_root &&
    bl64_check_parameter 'MY_VERSION' &&
    s64_core_lib_task_show_setup \
      'MY_VERSION' &&
    bl64_ui_ask_confirmation 'the operation can break the system. Ensure there is backup and recovery media.'
}

bl64_lib_script_version_set '1.1.0'
bl64_msg_help_set_about 'Remove specific kernel version packages'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
case "$BL64_OS_DISTRO" in
  ${BL64_OS_UB}-*) my_remove_ubuntu ;;
  ${BL64_OS_OL}-*) my_remove_oraclelinux ;;
  *) bl64_check_rise_task_unsupported ;;
esac
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
