#!/usr/bin/env bash
# template-module-lib: 2.0.0
#######################################
# K8S / Lib
#
# Version: 2.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-k8s.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Functions
#

function s64_k8s_lib_setup() {
  bl64_dbg_app_show_function

  bl64_k8s_setup
}

function s64_k8s_lib_cli_set_ns() {
  bl64_dbg_app_show_function "$@"
  local namespace="$1"
  # shellcheck disable=SC2154
  if [[ "$namespace" == "$BL64_VAR_DEFAULT" ]]; then
    printf -- '--all-namespaces'
  else
    printf -- '--namespace %s' "${namespace}"
  fi
}

function s64_k8s_lib_cli_set_output() {
  bl64_dbg_app_show_function "$@"
  local expand="$1"
  # shellcheck disable=SC2154
  case "$expand" in
  "$BL64_VAR_DEFAULT") printf -- '' ;;
  'json') printf -- '--output json' ;;
  *) printf -- '' ;;
  esac
}
