#!/usr/bin/env bash
# template-task: 3.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/k8s.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

declare MY_CPU_LIMIT='100m'
declare MY_MEMORY_LIMIT='1024Mi'
declare MY_CPU_REQUEST='50m'
declare MY_MEMORY_REQUEST='512Mi'
declare MY_POD_NAME='sysop64-shell'
declare MY_COMMAND='shell_run'
declare MY_OPTION=''
declare MY_NAMESPACE='default'
declare MY_CONTAINER_IMAGE="$BL64_VAR_DEFAULT"
declare MY_CONTAINER_ENTRYPOINT="$BL64_VAR_DEFAULT"

#
# Functions
#

function my_shell_run() {
  bl64_dbg_app_show_function "$@"
  local namespace="$1"
  local image="$2"
  local entrypoint="$3"
  local overrides_json=''

  bl64_msg_show_task "Run interactive shell (${namespace}/${MY_POD_NAME} -> ${image})"
  printf -v overrides_json '
  { "spec": {
      "restartPolicy": "Never",
      "containers": [
        {
          "name": "%s",
          "image": "%s",
          "imagePullPolicy": "IfNotPresent",
          "command": ["%s"],
          "resources": {
            "requests": {
              "cpu": "%s",
              "memory": "%s"
            },
            "limits": {
              "cpu": "%s",
              "memory": "%s"
            }
          },
          "stdin": true,
          "tty": true
        }
      ]
    }
  }
  ' "$MY_POD_NAME" "$image" "$entrypoint" "$MY_CPU_REQUEST" "$MY_MEMORY_REQUEST" "$MY_CPU_LIMIT" "$MY_MEMORY_LIMIT"

  bl64_k8s_run_kubectl "$BL64_VAR_DEFAULT" \
    run \
    --attach \
    --rm \
    --tty \
    --stdin \
    --restart=Never \
    --namespace="$namespace" \
    --image="$image" \
    --overrides="$overrides_json" \
    "$MY_POD_NAME" \
    -- "$entrypoint"
}

function my_initialize() {
  bl64_dbg_app_show_function
  [[ -n "$MY_OPTION" ]] || { bl64_msg_help_show && return 1; }
  s64_k8s_lib_setup ||
    return $?
  [[ "$MY_CONTAINER_ENTRYPOINT" == "$BL64_VAR_DEFAULT" ]] && MY_CONTAINER_ENTRYPOINT='sh'
  [[ "$MY_CONTAINER_IMAGE" == "$BL64_VAR_DEFAULT" ]] && MY_CONTAINER_IMAGE='alpine'
  bl64_msg_show_about
  bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
    'MY_NAMESPACE' \
    'MY_CONTAINER_IMAGE' \
    'MY_CONTAINER_ENTRYPOINT' \
    'MY_CPU_REQUEST' \
    'MY_MEMORY_REQUEST' \
    'MY_CPU_LIMIT' \
    'MY_MEMORY_LIMIT' \
    'MY_POD_NAME'
}

#
# Main
#

bl64_lib_script_version_set '3.1.0'
bl64_msg_help_usage_set '[-s] [-i Image] [-e EntryPoint] [-n NameSpace] [-V Verbose] [-D Debug] [-h]'
bl64_msg_help_about_set 'K8S / Pod / Run / Shell'
bl64_msg_help_parameters_set \
  '-s           : Run interactive shell (Default)
-h           : Show help
-i Image     : Full image path for the container. Default: alpine
-e EntryPoint: Command to run in the container. Default: sh
-n NameSpace : K8S namespace where the pod will run. Default: default
-V Verbose   : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
-D Debug     : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
'

while getopts ':si:n:e:V:D:h' MY_OPTION; do
  case "$MY_OPTION" in
    s) MY_COMMAND='shell_run' ;;
    n) MY_NAMESPACE="$OPTARG" ;;
    i) MY_CONTAINER_IMAGE="$OPTARG" ;;
    e) MY_CONTAINER_ENTRYPOINT="$OPTARG" ;;
    V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
    D) S64_CORE_SET_DEBUG="$OPTARG" ;;
    h) bl64_msg_help_show && exit 0 ;;
    *) bl64_msg_help_show && exit 1 ;;
  esac
done
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && s64_core_lib_set_verbose && my_initialize || exit $?

bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$MY_COMMAND"
"my_${MY_COMMAND}" "$MY_NAMESPACE" "$MY_CONTAINER_IMAGE" "$MY_CONTAINER_ENTRYPOINT"
bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$MY_COMMAND"
