#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_AT64="${HOME}/at64"
[[ ! -d "$S64_CORE_PATH_AT64" ]] && S64_CORE_PATH_AT64='/opt'
declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-${S64_CORE_PATH_AT64}/sysop64}"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/k8s-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

declare MY_NAMESPACE="${1:-}"
declare MY_TARGET_POD="${2:-}"
declare MY_TARGET_CONTAINER="${3:-}"

function my_initialize() {
  bl64_dbg_app_show_function
  bl64_msg_show_about
  bl64_check_parameter 'MY_NAMESPACE' &&
    bl64_check_parameter 'MY_TARGET_POD' &&
    bl64_check_parameter 'MY_TARGET_CONTAINER' &&
    s64_k8s_lib_setup &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'MY_NAMESPACE' \
      'MY_TARGET_POD' \
      'MY_TARGET_CONTAINER' &&
    bl64_msg_show_warning 'be aware that disruptive commands can shutdown the running container (e.g.: exit, CTRL+C, CTRL+D, etc.)'
  bl64_msg_show_warning "once done, kill the current shell to exit without stopping the container: kill ${$})" &&
    bl64_ui_ask_proceed 'do you want to proceed with the attachment operation?'
}

bl64_lib_script_version_set '1.0.2'
bl64_msg_help_about_set 'Attach local terminal to the STDIN and STDOUT of a running container'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_lib_var_is_default "$MY_TARGET_CONTAINER" && MY_TARGET_CONTAINER=''
bl64_k8s_run_kubectl \
  "$BL64_VAR_DEFAULT" \
  attach \
  --quiet \
  --tty \
  --stdin \
  --namespace="$MY_NAMESPACE" \
  --container="$MY_TARGET_CONTAINER" \
  "$MY_TARGET_POD"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
