#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/git.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

declare MY_BRANCH_NAME="${1:-}"
declare MY_REMOTE_NAME="${2:-}"

function my_destroy() {
  bl64_msg_show_task 'destroy local branch'
  bl64_vcs_run_git \
    branch \
    --delete \
    --force \
    "$MY_BRANCH_NAME"

  if [[ -n "$MY_REMOTE_NAME" ]]; then
    bl64_msg_show_task 'destroy remote branch'
    bl64_vcs_run_git \
      push \
      --delete \
      "$MY_REMOTE_NAME" \
      "$MY_BRANCH_NAME"
    bl64_vcs_run_git \
      remote \
      prune \
      "$MY_REMOTE_NAME"
  fi
  return 0
}

function my_initialize() {
  bl64_dbg_app_show_function
  bl64_msg_show_about
  if [[ "$MY_BRANCH_NAME" =~ (main|master) ]]; then
    bl64_msg_show_error 'destroying the main branch is not supported'
    return 1
  fi
  s64_git_lib_setup &&
    bl64_check_parameter 'MY_BRANCH_NAME' &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'MY_BRANCH_NAME' \
      'MY_REMOTE_NAME' &&
    bl64_ui_ask_proceed 'destroy branch even if not fully merged?'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'Destroy local GIT branch, and optionally from remote'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && s64_core_lib_set_verbose && my_initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_destroy
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
