#!/usr/bin/env bash
# template: 1.0.0
# template-import: 1.0.0
#######################################
# GIT / File / History / Show Commits
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# template-import: 1.0.0
declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck source-path=SCRIPTDIR/..
source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" ||
  { echo "Error: unable to load bashlib64" && exit 1; }
# shellcheck source-path=SCRIPTDIR/..
source "${SYSOP64_CORE_PATH_ROOT}/git/git-lib" || { echo "Error: unable to load module library" && exit 1; }

#
# Functions
#

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'file_path'
}

#
# Main
#

declare file_path="${1:-}"
declare command='git-file-history-show-commits'

bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
initialize || exit $?

bl64_msg_show_batch_start "$command"
bl64_vcs_run_git \
  log \
  --all \
  --follow \
  --oneline \
  --decorate=short \
  --full-history \
  "$file_path"
bl64_msg_show_batch_finish $? "$command"
