#!/usr/bin/env bash
# template-module-lib: 2.0.0
#######################################
# ArgoCD / Lib
#
# Version: 1.2.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-k8s.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_ARGOCD_PATH_CLI="${S64_ARGOCD_PATH_CLI:-}"
  # Global Settings
  declare S64_ARGOCD_SET_CONNECTION='--core'
  declare S64_ARGOCD_SET_CONTEXT_NAME="${S64_ARGOCD_SET_CONTEXT_NAME:-argocdcli}"
}

#
# Functions
#

function s64_argocd_lib_setup() {
  bl64_dbg_app_show_function

  bl64_k8s_setup ||
    return $?

  if [[ -z "$S64_ARGOCD_PATH_CLI" ]]; then
    S64_ARGOCD_PATH_CLI="$(bl64_bsh_command_locate 'argocd')"
  else
    bl64_check_command "$S64_ARGOCD_PATH_CLI"
  fi
}

function s64_argocd_lib_run_argocd() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_ARGOCD_PATH_CLI" \
    --kube-context="$S64_ARGOCD_SET_CONTEXT_NAME" \
    $S64_ARGOCD_SET_CONNECTION \
    "$@"
  bl64_dbg_app_trace_stop
}
