#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/linux.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

function my_disable_current() {
  bl64_dbg_app_show_function
  local manager=''
  case "$BL64_OS_DISTRO" in
    ${BL64_OS_FD}-4[1-3].?)
      manager='sddm'
      bl64_msg_show_phase "disable display manager (${manager})"
      s64_linux_lib_run_systemctl stop "$manager"
      s64_linux_lib_run_systemctl disable "$manager" --force
      ;;
    *)
      bl64_check_alert_unsupported
      return $?
      ;;
  esac
}

function my_enable_new() {
  bl64_dbg_app_show_function
  case "$BL64_OS_DISTRO" in
    ${BL64_OS_FD}-4[1-3].?)
      bl64_msg_show_phase 'enable GDM'
      s64_linux_lib_run_systemctl enable gdm --force
      s64_linux_lib_run_systemctl start gdm
      ;;
    *)
      bl64_check_alert_unsupported
      return $?
      ;;
  esac
}

function my_switch() {
  bl64_dbg_app_show_function
  my_disable_current
  my_enable_new
}

function my_initialize() {
  bl64_dbg_app_show_function
  bl64_msg_show_about
  s64_linux_lib_setup &&
    bl64_check_privilege_root &&
    bl64_ui_ask_proceed 'is the task being run from a terminal and not from the desktop environment?'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'Switch to GDM display manager'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && s64_core_lib_set_verbose && my_initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_switch
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
