#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/firewalld.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

declare MY_POLICY_ID="${1:-allow-ingress-to-egress}"
declare MY_ZONE_ID_INGRESS="${2:-internal}"
declare MY_ZONE_ID_EGRESS="${3:-external}"

function my_initialize() {
  bl64_dbg_app_show_function
  s64_firewalld_lib_setup &&
    bl64_check_privilege_root &&
    bl64_check_parameter 'MY_POLICY_ID' &&
    bl64_check_parameter 'MY_ZONE_ID_INGRESS' &&
    bl64_check_parameter 'MY_ZONE_ID_EGRESS' &&
    s64_core_lib_task_show_setup \
      'MY_POLICY_ID' \
      'MY_ZONE_ID_INGRESS' \
      'MY_ZONE_ID_EGRESS'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_set_about 'Create firewall policy to allow inter-zone forwarding'
bl64_msg_help_set_usage 'MY_POLICY_ID MY_ZONE_ID_INGRESS MY_ZONE_ID_EGRESS'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
s64_firewalld_lib_run_firewall_cmd --permanent --new-policy "$MY_POLICY_ID" &&
s64_firewalld_lib_run_firewall_cmd --permanent --policy "$MY_POLICY_ID" --add-ingress-zone="$MY_ZONE_ID_INGRESS" &&
s64_firewalld_lib_run_firewall_cmd --permanent --policy "$MY_POLICY_ID" --add-egress-zone="$MY_ZONE_ID_EGRESS" &&
s64_firewalld_lib_run_firewall_cmd --permanent --policy "$MY_POLICY_ID" --set-target ACCEPT
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"

