#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/macos.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

declare MY_PREFERENCE_NAME="${1:-}"
declare MY_PREFERENCE_FILE="${S64_MACOS_PATH_CFG_PREFERENCES}/${MY_PREFERENCE_NAME}.plist"

function my_initialize() {
  bl64_dbg_app_show_function
  bl64_msg_show_about
  s64_macos_lib_setup &&
    bl64_check_parameter 'MY_PREFERENCE_NAME' &&
    bl64_check_file 'MY_PREFERENCE_FILE' &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'MY_PREFERENCE_NAME' \
      'MY_PREFERENCE_FILE'
}

bl64_lib_script_version_set '1.0.1'
bl64_msg_help_about_set 'Show MacOS UI Preferences file content'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && s64_core_lib_set_verbose && my_initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
s64_macos_lib_run_plistbuddy \
  -c 'print' \
  "$MY_PREFERENCE_FILE"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
