#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/cilium.lib" && source "${S64_CORE_PATH_LIB}/k8s.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

declare MY_API_FQDN="${1:-}"

function my_initialize() {
  bl64_dbg_app_show_function
  s64_cilium_lib_setup &&
    S64_CORE_SET_MODULE_PRIMARY='NO' s64_k8s_lib_setup &&
    bl64_check_privilege_not_root &&
    bl64_check_parameter 'MY_API_FQDN' &&
    bl64_msg_show_doc "Reference: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/" &&
    bl64_msg_show_doc "Reference: https://docs.cilium.io/en/stable/network/l2-announcements/" &&
    bl64_msg_show_info 'Deployment options:
  - kubeProxyReplacement: replace kube-proxy
  - l2announcements: enable L2 announcements' &&
    s64_core_lib_task_show_setup \
      'S64_CILIUM_SET_VERSION' \
      'MY_API_FQDN' \
      'S64_K8S_SET_CLUSTER_API_PORT'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_set_about 'Deploy service to K8S cluster. Edge configuration profile'
bl64_msg_help_set_usage 'MY_API_FQDN'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
s64_cilium_lib_run_cilium \
  install \
  --set kubeProxyReplacement=true \
  --set l2announcements.enabled=true \
  --set "k8sServiceHost=${MY_API_FQDN}" \
  --set "k8sServicePort=${S64_K8S_SET_CLUSTER_API_PORT}" \
  --version "$S64_CILIUM_SET_VERSION"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
