#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/cilium.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

declare MY_TARGET_VERSION="${1:-}"
declare MY_VALUES_FILE="${2:-$BL64_VAR_DEFAULT}"
declare MY_CHART_REPOSITORY="${3:-$BL64_VAR_DEFAULT}"
declare MY_CHART_SOURCE="${4:-$BL64_VAR_DEFAULT}"

function my_initialize() {
  bl64_dbg_app_show_function
  ! bl64_lib_var_is_set "$MY_VALUES_FILE" && MY_VALUES_FILE=''
  ! bl64_lib_var_is_set "$MY_CHART_SOURCE" && MY_CHART_SOURCE=''
  ! bl64_lib_var_is_set "$MY_CHART_REPOSITORY" && MY_CHART_REPOSITORY=''
  s64_cilium_lib_setup &&
    bl64_check_privilege_not_root &&
    bl64_check_parameter 'MY_TARGET_VERSION' &&
    s64_core_lib_task_show_setup \
      'MY_TARGET_VERSION' \
      'MY_VALUES_FILE' \
      'MY_CHART_REPOSITORY' \
      'MY_CHART_SOURCE'
}

bl64_lib_script_version_set '2.0.0'
bl64_msg_help_set_about 'Deploy service to K8S cluster. Default configuration profile'
bl64_msg_help_set_usage 'MY_TARGET_VERSION [MY_VALUES_FILE] [MY_CHART_REPOSITORY] [MY_CHART_SOURCE]'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
s64_cilium_lib_run_cilium \
  install \
  ${MY_CHART_REPOSITORY:+--repository "$MY_CHART_REPOSITORY"} \
  ${MY_CHART_SOURCE:+--chart-directory "$MY_CHART_SOURCE"} \
  ${MY_VALUES_FILE:+--values "$MY_VALUES_FILE"} \
  --version "$MY_TARGET_VERSION"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
