#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/k8s.lib" || { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

declare MY_TYPE="${1:-$BL64_VAR_DEFAULT}"
declare MY_OBJECT="${2:-$BL64_VAR_DEFAULT}"
declare MY_NAMESPACE="${3:-$BL64_VAR_DEFAULT}"

function my_get_type() {
  bl64_dbg_app_show_function
  local type="$1"
  local object="$2"

  # shellcheck disable=SC2086,SC2046
  bl64_k8s_run_kubectl \
    get \
    "$(s64_k8s_lib_cli_set_format)" \
    $(s64_k8s_lib_cli_set_ns "$MY_NAMESPACE") \
    "$type" $object
}

function my_list() {
  bl64_dbg_app_show_function
  local current=''

  bl64_lib_var_is_default "$MY_OBJECT" && MY_OBJECT=''
  if bl64_lib_var_is_default "$MY_TYPE"; then
    MY_TYPE="$(bl64_k8s_run_kubectl \
      api-resources \
      --namespaced=true \
      --sort-by='name' \
      "$(s64_k8s_lib_cli_set_format 'name')")"
  fi

  for current in $MY_TYPE; do
    bl64_msg_show_separator "$current"
    my_get_type "$current" "$MY_OBJECT"
  done
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_k8s_lib_setup &&
    bl64_msg_show_setup "$S64_CORE_LABEL_TASK_PARAMETERS" \
      'MY_NAMESPACE' \
      'MY_TYPE' \
      'MY_OBJECT'
}

bl64_lib_script_version_set '2.0.1'
bl64_msg_help_about_set 'Show deployed Kubernetes objects manifest'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_list
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
