#!/usr/bin/env bash
# template-task-base: 1.1.0
#######################################
# X_MODULE_NAME_X / [X_SUBMODULE_NAME_X /] X_APP_NAME_X
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

#
# Globals
#

# X_GLOBALS_PLACEHOLDER_X

#
# Functions
#

function X_COMMAND_X() {
  bl64_dbg_app_show_function "$@"
  # X_COMMAND_PLACEHOLDER_X
}

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'main_command' ||
    { help && return 1; }

  # X_INIT_PLACEHOLDER_X
  return 0
}

function help() {
  bl64_msg_show_usage \
    '-x [-V Verbose] [-D Debug] [-h]' \
    'X_MODULE_NAME_X / [X_SUBMODULE_NAME_X /] X_APP_NAME_X' \
    '
    -x         : X_COMMAND_INFO_X
    ' '
    -h         : Show help
    ' '
    -V Verbose : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
    -D Debug   : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
    '
}

#
# Main
#

declare main_command="$BL64_VAR_NULL"
declare main_option=''

(($# == 0)) && help && exit 1
while getopts ':xV:D:h' main_option; do
  case "$main_option" in
  x) main_command='X_COMMAND_X' ;;
  V) S64_CORE_SET_VERBOSE="$OPTARG" ;;
  D) S64_CORE_SET_DEBUG="$OPTARG" ;;
  h) help && exit 0 ;;
  *) help && exit 1 ;;
  esac
done
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" &&
  initialize || exit $?

bl64_msg_show_batch_start "${BL64_SCRIPT_ID}:$main_command"
"${main_command}"
bl64_msg_show_batch_finish $? "${BL64_SCRIPT_ID}:$main_command"
