#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/socat.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

declare MY_BROADCAST_INTERFACE="${1:-}"
declare MY_BROADCAST_IP="${2:-239.255.0.10}"
declare MY_BROADCAST_PORT="${3:-23900}"
declare MY_PAYLOAD="${4:-hello-world}"

function my_initialize() {
  bl64_dbg_app_show_function
  s64_socat_lib_setup &&
    bl64_check_parameter 'MY_BROADCAST_INTERFACE' &&
    s64_core_lib_task_show_setup \
      'MY_BROADCAST_INTERFACE' \
      'MY_BROADCAST_IP' \
      'MY_BROADCAST_PORT' \
      'MY_PAYLOAD'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_set_about 'Send a string using UDP multicast'
bl64_msg_help_set_usage 'MY_BROADCAST_INTERFACE [MY_BROADCAST_IP] [MY_BROADCAST_PORT] [MY_PAYLOAD]'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
echo "$MY_PAYLOAD" |
  s64_socat_lib_run_socat \
    STDIN \
    "UDP4-DATAGRAM:${MY_BROADCAST_IP}:${MY_BROADCAST_PORT},ip-multicast-loop=1,ip-multicast-if=${MY_BROADCAST_INTERFACE}"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
