#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/k3s.lib" &&
  source "${S64_CORE_PATH_ROOT}/core/openssh.lib" ||
  { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

declare MY_CONTROL_IP="${1:-}"
declare MY_CONTROL_USER="${2:-}"

function my_kubeconfig_get() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Get kubeconfig file from remote control plane'
  s64_openssh_lib_run_scp \
    -O \
    "${MY_CONTROL_USER}@${MY_CONTROL_IP}:${S64_K3S_PATH_CFG_K3S_SERVER}" \
    "$S64_K3S_PATH_CFG_K8S_KUBECTL"
}

function my_kubeconfig_patch() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Patch kubeconfig cluster API address'
  bl64_txt_line_replace_sed "$S64_K3S_PATH_CFG_K8S_KUBECTL" "s/127.0.0.1/${MY_CONTROL_IP}/g"
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_openssh_lib_setup &&
    s64_k3s_lib_setup &&
    bl64_check_parameter 'MY_CONTROL_IP' &&
    bl64_check_parameter 'MY_CONTROL_USER' &&
    s64_core_lib_show_setup \
      'MY_CONTROL_IP' \
      'MY_CONTROL_USER' \
      'S64_K3S_PATH_CFG_K3S_SERVER' \
      'S64_K3S_PATH_CFG_K8S_KUBECTL'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'Import kubeconf file from a cluster control plane'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_kubeconfig_get &&
  my_kubeconfig_patch
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
