#!/usr/bin/env bash
# template: 1.0.0
#######################################
# Kind / Lib
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_KIND_PATH_CLI="${S64_KIND_PATH_CLI:-}"

  # Cluster definition
  S64_KIND_PATH_CLUSTER_CONFIG="${S64_KIND_PATH_CLUSTER_CONFIG:-}"
  S64_KIND_SET_CLUSTER_NAME="${S64_KIND_SET_CLUSTER_NAME:-default}"
}

#
# Functions
#

function s64_kind_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$S64_KIND_PATH_CLI" ]]; then
    if [[ -x '/home/linuxbrew/.linuxbrew/bin/kind' ]]; then
      S64_KIND_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/kind'
    elif [[ -x '/opt/homebrew/bin/kind' ]]; then
      S64_KIND_PATH_CLI='/opt/homebrew/bin/kind'
    elif [[ -x '/usr/local/bin/kind' ]]; then
      S64_KIND_PATH_CLI='/usr/local/bin/kind'
    elif [[ -x '/usr/bin/kind' ]]; then
      S64_KIND_PATH_CLI='/usr/bin/kind'
    else
      bl64_check_alert_resource_not_found 'kind'
      return $?
    fi
  else
    bl64_check_command "$S64_KIND_PATH_CLI" ||
      return $?
  fi
}

function s64_kind_lib_run_kind() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  "$S64_KIND_PATH_CLI" \
    "$@"
  bl64_dbg_app_trace_stop
}
