#!/usr/bin/env bash
# template: 1.0.0
# template-import: 1.0.0
#######################################
# Linux / Package / Upgrade
#
# Version: 1.0.1
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#module-task
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck source-path=SCRIPTDIR/..
source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-cryp.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" ||
  { echo "Error: unable to load bashlib64" && exit 1; }
# shellcheck source-path=SCRIPTDIR/..
source "${SYSOP64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }

#
# Functions
#

function upgrade_ubuntu() {
  bl64_dbg_app_show_function
  bl64_ui_ask_confirmation 'Warning: the task will auto-remove and upgrade all packages to the latest version for the current distro release' &&
    bl64_msg_show_task 'auto-remove unused packages' &&
    bl64_pkg_run_apt autoremove "$BL64_PKG_SET_ASSUME_YES" &&
    bl64_msg_show_task 'prepare for upgrade' &&
    bl64_pkg_prepare &&
    bl64_msg_show_task 'upgrade all packages' &&
    bl64_pkg_run_apt upgrade \
      --with-new-pkgs \
      --show-progress \
      "$BL64_PKG_SET_ASSUME_YES"
}

function upgrade() {
  bl64_dbg_app_show_function
  case "$BL64_OS_DISTRO" in
  ${BL64_OS_UB}-*) upgrade_ubuntu ;;
  *) bl64_check_alert_unsupported ;;
  esac
}

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_privilege_root
}

#
# Main
#

declare command='upgrade'
declare debug="$BL64_DBG_TARGET_NONE"
declare verbose="$BL64_MSG_VERBOSE_ALL"

bl64_dbg_set_level "$debug" && bl64_msg_set_level "$verbose" || exit $?
initialize || exit $?

bl64_msg_show_batch_start "$command"
upgrade
bl64_msg_show_batch_finish $? "$command"
