#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/k8s.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

declare MY_NAMESPACE="${1:-}"
declare MY_GATEWAY="${2:-}"

function my_initialize() {
  bl64_dbg_app_show_function
  s64_k8s_lib_setup &&
    bl64_check_parameter 'MY_NAMESPACE' &&
    bl64_check_parameter 'MY_GATEWAY' &&
    s64_core_lib_task_show_setup \
      'MY_NAMESPACE' \
      'MY_GATEWAY'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_set_about 'Show deployed K8S Gateways status'
bl64_msg_help_set_usage 'MY_NAMESPACE MY_GATEWAY'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_k8s_run_kubectl \
  describe \
  --show-events=true \
  --namespace="$MY_NAMESPACE" \
  gateway \
  "$MY_GATEWAY"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
