#!/usr/bin/env bash
# template: 1.0.0
#######################################
# Restic / Lib
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_RESTIC_PATH_CLI="${S64_RESTIC_PATH_CLI:-}"
  declare S64_RESTIC_PATH_REPOSITORY="${S64_RESTIC_PATH_REPOSITORY:-}"
  declare S64_RESTIC_PASSWORD="${S64_RESTIC_PASSWORD:-}"
  export RESTIC_REPOSITORY=''
  export RESTIC_PASSWORD=''
}

#
# Functions
#

function s64_restic_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$S64_RESTIC_PATH_CLI" ]]; then
    if [[ -x '/home/linuxbrew/.linuxbrew/bin/restic' ]]; then
      S64_RESTIC_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/restic'
    elif [[ -x '/opt/homebrew/bin/restic' ]]; then
      S64_RESTIC_PATH_CLI='/opt/homebrew/bin/restic'
    elif [[ -x '/usr/local/bin/restic' ]]; then
      S64_RESTIC_PATH_CLI='/usr/local/bin/restic'
    elif [[ -x '/usr/bin/restic' ]]; then
      S64_RESTIC_PATH_CLI='/usr/bin/restic'
    else
      bl64_check_alert_resource_not_found 'restic'
      return $?
    fi
  else
    bl64_check_command "$S64_RESTIC_PATH_CLI" ||
      return $?
  fi
  bl64_check_privilege_root &&
    bl64_check_export 'S64_RESTIC_PATH_REPOSITORY' &&
    bl64_check_export 'S64_RESTIC_PASSWORD'
}

function s64_restic_lib_run_restic() {
  bl64_dbg_app_show_function "$@"
  RESTIC_REPOSITORY="$S64_RESTIC_PATH_REPOSITORY"
  RESTIC_PASSWORD="$S64_RESTIC_PASSWORD"
  bl64_dbg_app_trace_start
  "$S64_RESTIC_PATH_CLI" \
    --verbose \
    "$@"
  bl64_dbg_app_trace_stop
}
