#!/usr/bin/env bash
# template-one: 3.0.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_AT64="${HOME}/at64"
[[ ! -d "$S64_CORE_PATH_AT64" ]] && S64_CORE_PATH_AT64='/opt'
declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-${S64_CORE_PATH_AT64}/sysop64}"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/restic-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

function initialize() {
  bl64_dbg_app_show_function
  s64_restic_lib_setup &&
    bl64_check_parameter 'BACKUP_TAG' &&
    bl64_check_parameter 'BACKUP_SOURCE' &&
    bl64_check_path_absolute "$BACKUP_SOURCE" &&
    bl64_check_path "$BACKUP_SOURCE" &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'S64_RESTIC_PATH_REPOSITORY' \
      'BACKUP_SOURCE' \
      'BACKUP_TAG'
}

declare BACKUP_TAG="${1:-}"
declare BACKUP_SOURCE="${2:-}"

bl64_lib_script_version_set '1.0.3'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_msg_show_task 'create backup'
s64_restic_lib_run_restic \
  --tag "$BACKUP_TAG" \
  backup \
  "$BACKUP_SOURCE"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
