#!/usr/bin/env bash
# template-one: 2.0.0
#######################################
# Restic / Backup / Restore
#
# Version: 2.0.1
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/restic-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Functions
#

function initialize() {
  bl64_dbg_app_show_function
  s64_restic_lib_setup &&
    bl64_check_parameter 'BACKUP_TAG' &&
    bl64_check_parameter 'DESTINATION'
}

#
# Main
#

declare BACKUP_TAG="${1:-}"
declare DESTINATION="${2:-}"
declare BACKUP_ID="${3:-latest}"
declare BACKUP_HOST="${4:-}"

bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_msg_show_info "
Backup Tag : ${BACKUP_TAG}
Backup ID  : ${BACKUP_ID}
Backup Host: ${BACKUP_HOST}
Destination: ${DESTINATION}"

bl64_ui_ask_confirmation 'Warning: DESTINATION content will be replaced using absolute paths from backup' &&
  s64_restic_lib_run_restic \
    --verbose \
    --target "$DESTINATION" \
    --tag "$BACKUP_TAG" \
    ${BACKUP_HOST:+--host "$BACKUP_HOST"} \
    restore \
    "$BACKUP_ID"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
