#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/skopeo.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

declare MY_CONTAINER_IMAGE="${1:-}"
declare MY_CONTAINER_URL=''

function my_initialize() {
  bl64_dbg_app_show_function
  s64_skopeo_lib_setup &&
    bl64_check_export 'S64_SKOPEO_REGISTRY_SERVER' &&
    bl64_check_parameter 'MY_CONTAINER_IMAGE' &&
    MY_CONTAINER_URL="docker://${S64_SKOPEO_REGISTRY_SERVER}/${MY_CONTAINER_IMAGE}" &&
    s64_core_lib_task_show_setup \
      'S64_SKOPEO_REGISTRY_SERVER' \
      'MY_CONTAINER_IMAGE' \
      'MY_CONTAINER_URL'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_set_about 'List image tags in a container registry'
bl64_msg_help_set_usage 'MY_CONTAINER_IMAGE'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
s64_skopeo_lib_run_skopeo \
  list-tags \
  "$(s64_skopeo_lib_cli_set_insecure)" \
  "$MY_CONTAINER_URL"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
