#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/k8s.lib" || { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

declare MY_KUBEADM_CONFIG="${1:-}"

function my_stop_server() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Stop control plane server'
  s64_k8s_lib_run_kubeadm \
    reset \
    ${MY_KUBEADM_CONFIG:+--config="$MY_KUBEADM_CONFIG"} \
    --force
}

function my_remove_paths() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Remove configuration and runtime paths'
  bl64_fs_path_remove \
    "$S64_K8S_PATH_CFG_CLUSTER_BASE" \
    "$S64_K8S_PATH_CFG_CNI_BASE" \
    "$S64_K8S_PATH_VAR_CNI_BASE" \
    "$S64_K8S_PATH_VAR_ETCD_BASE" \
    "$S64_K8S_PATH_CFG_KUBECTL_BASE"
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_k8s_lib_setup &&
    bl64_check_privilege_root &&
    s64_core_lib_show_setup \
      'S64_K8S_PATH_CFG_CLUSTER_BASE' \
      'S64_K8S_PATH_CFG_CNI_BASE' \
      'S64_K8S_PATH_VAR_CNI_BASE' \
      'S64_K8S_PATH_VAR_ETCD_BASE' \
      'S64_K8S_PATH_CFG_KUBECTL_BASE' \
      'MY_KUBEADM_CONFIG' &&
    bl64_ui_ask_proceed 'Remove all cluster services on the current node?'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'Destroy control plane node'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_stop_server
my_remove_paths
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
