#!/usr/bin/env bash
# template: 1.0.0
# template-import: 1.0.0
#######################################
# RSync / Clone / Dir / List / Delta
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck source-path=SCRIPTDIR/..
source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${SYSOP64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" ||
  { echo "Error: unable to load bashlib64" && exit 1; }
# shellcheck source-path=SCRIPTDIR/..
source "${SYSOP64_CORE_PATH_ROOT}/rsync/rsync-lib" || { echo "Error: unable to load module library" && exit 1; }

#
# Functions
#

function initialize() {
  bl64_dbg_app_show_function
  rsync_lib_setup &&
    bl64_check_parameter 'rsync_clone_from' &&
    bl64_check_parameter 'rsync_clone_to' &&
    bl64_check_directory "$rsync_clone_from"
}

#
# Main
#

declare command='send'
declare rsync_clone_from="${1:-}"
declare rsync_clone_to="${2:-}"

bl64_dbg_set_level "$SYSOP64_CORE_SET_DEBUG" && bl64_msg_set_level "$SYSOP64_CORE_SET_VERBOSE" || exit $?
initialize || exit $?

bl64_msg_show_batch_start "$command"
bl64_msg_show_task "Show delta between source and destination (${rsync_clone_from} -> ${rsync_clone_to})"
# shellcheck disable=SC2086
rsync_lib_run_rsync \
  $SYSOP64_RSYNC_OPTIONS_COMMON \
  --dry-run \
  "$rsync_clone_from" \
  "$rsync_clone_to"
bl64_msg_show_batch_finish $? "$command"
