#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/rsync.lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

declare MY_DIR_NAME="${1:-}"
declare MY_BASE_FROM="${2:-}"
declare MY_BASE_TO="${3:-}"

function my_initialize() {
  bl64_dbg_app_show_function
  bl64_msg_show_about
  s64_rsync_lib_setup &&
    bl64_check_parameter 'MY_DIR_NAME' &&
    bl64_check_parameter 'MY_BASE_FROM' &&
    bl64_check_parameter 'MY_BASE_TO' &&
    bl64_check_directory "$MY_BASE_FROM" &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'MY_DIR_NAME' \
      'MY_BASE_FROM' \
      'MY_BASE_TO' &&
    bl64_ui_ask_confirmation 'warning: destination content will be replaced'
}

bl64_lib_script_version_set '2.0.0'
bl64_msg_help_about_set 'Copy files between Linux paths: keep source files'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && s64_core_lib_set_verbose && my_initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
# shellcheck disable=SC2086
s64_rsync_lib_run_rsync \
  $S64_RSYNC_SET_COMMON \
  $S64_RSYNC_SET_LOCAL \
  $S64_RSYNC_SET_COPY \
  "${MY_BASE_FROM}/${MY_DIR_NAME}/" \
  "${MY_BASE_TO}/${MY_DIR_NAME}"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
