#!/usr/bin/env bash
# template-one: 2.0.0
#######################################
# RSync / Clone / Dir / Local
#
# Version: 1.0.2
#
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/rsync-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Functions
#

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_privilege_root &&
    bl64_check_parameter 'RSYNC_CLONE_FROM' &&
    bl64_check_parameter 'RSYNC_CLONE_TO' &&
    bl64_check_directory "$RSYNC_CLONE_FROM" &&
    s64_rsync_lib_setup
}

#
# Main
#

declare RSYNC_CLONE_FROM="${1:-}"
declare RSYNC_CLONE_TO="${2:-}"

bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_msg_show_info 'Copy files from Linux path to Linux path. Operation is privileged, source file ownership is kept.'
# shellcheck disable=SC2086
bl64_ui_ask_confirmation "Warning: destination content will be replaced (${RSYNC_CLONE_FROM} -> ${RSYNC_CLONE_TO})" &&
  s64_rsync_lib_run_rsync \
    $S64_RSYNC_OPTIONS_COMMON \
    $S64_RSYNC_OPTIONS_LOCAL \
    --recursive \
    --delete \
    --owner \
    --group \
    --times \
    --numeric-ids \
    "$RSYNC_CLONE_FROM" \
    "$RSYNC_CLONE_TO"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
