#!/usr/bin/env bash
# template-one: 3.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_AT64="${HOME}/at64"
[[ ! -d "$S64_CORE_PATH_AT64" ]] && S64_CORE_PATH_AT64='/opt'
declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-${S64_CORE_PATH_AT64}/sysop64}"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/rsync-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

function my_initialize() {
  bl64_dbg_app_show_function
  s64_rsync_lib_setup &&
    bl64_check_parameter 'MY_RSYNC_CLONE_FROM' &&
    bl64_check_parameter 'MY_RSYNC_CLONE_TO' &&
    bl64_check_directory "$MY_RSYNC_CLONE_FROM" &&
    bl64_msg_show_setup 'Copy files between Linux and CIFS paths. The operation will try to adapt linux files attributes and names to CIFS equivalents.' \
      'S64_RSYNC_OPTIONS_COMMON' \
      'MY_RSYNC_CLONE_FROM' \
      'MY_RSYNC_CLONE_TO' &&
    bl64_ui_ask_confirmation "Warning: destination content will be replaced (${MY_RSYNC_CLONE_FROM} -> ${MY_RSYNC_CLONE_TO})"
}

declare MY_RSYNC_CLONE_FROM="${1:-}"
declare MY_RSYNC_CLONE_TO="${2:-}"

bl64_lib_script_version_set '1.0.3'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
# shellcheck disable=SC2086
s64_rsync_lib_run_rsync \
  $S64_RSYNC_OPTIONS_COMMON \
  --recursive \
  --no-links \
  --no-perms \
  --no-acls \
  --no-owner \
  --no-group \
  --no-devices \
  --numeric-ids \
  "$MY_RSYNC_CLONE_FROM" \
  "$MY_RSYNC_CLONE_TO"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
