#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/rsync.lib" || { s64_core_lib_check_module_load && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

declare MY_DIR_NAME="${1:-}"
declare MY_BASE_FROM="${2:-}"
declare MY_BASE_TO="${3:-}"

function my_initialize() {
  bl64_dbg_app_show_function
  s64_core_lib_show_about
  s64_rsync_lib_setup &&
    bl64_check_parameter 'MY_DIR_NAME' &&
    bl64_check_parameter 'MY_BASE_FROM' &&
    bl64_check_parameter 'MY_BASE_TO' &&
    bl64_check_directory "$MY_BASE_FROM" &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'MY_DIR_NAME' \
      'MY_BASE_FROM' \
      'MY_BASE_TO'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'Check files between Linux paths: report differences'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

bl64_msg_show_info 'Change reference:

< : means that a file is being transferred to the remote host (sent)
> : means that a file is being transferred to the local host (received)
c : means that a local change/creation is occurring for the item
h : means that the item is a hard link to another item
. : means that the item is not being updated (though it might have attributes that are being modified)
* : means that the rest of the itemized-output area contains a message
'

bl64_msg_show_separator 'summary of changes'
# shellcheck disable=SC2086
s64_rsync_lib_run_rsync \
  --checksum \
  --recursive \
  --dry-run \
  --itemize-changes \
  --delete \
  $S64_RSYNC_SET_CIFS \
  "${MY_BASE_FROM}/${MY_DIR_NAME}/" \
  "${MY_BASE_TO}/${MY_DIR_NAME}"

bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
