#!/usr/bin/env bash
# template-task: 3.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_AT64="${HOME}/at64"
[[ ! -d "$S64_CORE_PATH_AT64" ]] && S64_CORE_PATH_AT64='/opt'
declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-${S64_CORE_PATH_AT64}/sysop64}"
# shellcheck source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

function my_module_list() {
  cd "$S64_CORE_PATH_ROOT" &&
    ls -1
}

function my_task_list() {
  local task=''
  [[ "$MY_MODULE" == 'core' || ! -d "${S64_CORE_PATH_ROOT}/${MY_MODULE}" ]] &&
    echo "Fatal: invalid SysOp64 module name" &&
    return 1
  cd "${S64_CORE_PATH_ROOT}/${MY_MODULE}" || return $?
  for task in "${MY_MODULE}"-*; do
    [[ -f "$task" ]] && echo "${task#${MY_MODULE}-}"
  done
}

function my_task_run() {
  local task="${S64_CORE_PATH_ROOT}/${MY_MODULE}/${MY_MODULE}-${MY_TASK}"
  [[ ! -x "$task" ]] &&
    echo "Fatal: invalid SysOp64 module/task name (${task})" &&
    return 1
  "$task" "$@"
}

declare MY_MODULE="${1:-}"
declare MY_TASK="${2:-}"

bl64_lib_script_version_set '1.1.0'
bl64_msg_help_usage_set 'sysop64 [MODULE] [TASK] [TASK-PARAMETERS]'
bl64_msg_help_about_set 'Run SysOp64 tasks'
# shellcheck disable=SC2016
bl64_msg_help_parameters_set \
  '
  MODULE         : Module name. If none, list them all
  TASK           : Task name. If none, list them all. Requires MODULE to be set
  TASK-PARAMETERS: Task parameters
'

if [[ -z "$MY_MODULE" ]]; then
  my_module_list
elif [[ -n "$MY_MODULE" && -z "$MY_TASK" ]]; then
  my_task_list
elif [[ -n "$MY_MODULE" && -n "$MY_TASK" ]]; then
  shift
  shift
  my_task_run "$@"
fi
