#!/usr/bin/env bash
# template: 1.0.0
#######################################
# Linux / Lib
#
# Version: 1.1.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

declare SYSOP64_LINUX_PATH_CLI_BADBLOCKS=''
declare SYSOP64_LINUX_PATH_CLI_BLKID=''
declare SYSOP64_LINUX_PATH_CLI_CRYPTSETUP=''
declare SYSOP64_LINUX_PATH_CLI_FSCK=''
declare SYSOP64_LINUX_PATH_CLI_JOURNALCTL=''
declare SYSOP64_LINUX_PATH_CLI_LSBLK=''
declare SYSOP64_LINUX_PATH_CLI_MDADM=''
declare SYSOP64_LINUX_PATH_CLI_MOUNT=''

#
# Functions
#

function linux_lib_setup() {
  bl64_dbg_app_show_function
  case "$BL64_OS_FLAVOR" in
  "$BL64_OS_FLAVOR_DEBIAN")
    SYSOP64_LINUX_PATH_CLI_BADBLOCKS='/usr/sbin/badblocks'
    SYSOP64_LINUX_PATH_CLI_BLKID='/usr/sbin/blkid'
    SYSOP64_LINUX_PATH_CLI_CRYPTSETUP='/usr/sbin/cryptsetup'
    SYSOP64_LINUX_PATH_CLI_FSCK='/usr/sbin/fsck'
    SYSOP64_LINUX_PATH_CLI_JOURNALCTL='/usr/bin/journalctl'
    SYSOP64_LINUX_PATH_CLI_LSBLK='/bin/lsblk'
    SYSOP64_LINUX_PATH_CLI_MDADM='/usr/sbin/mdadm'
    SYSOP64_LINUX_PATH_CLI_MOUNT='/bin/mount'
    ;;
  *) bl64_check_alert_unsupported ;;
  esac
}

function linux_lib_run_blkid() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$SYSOP64_LINUX_PATH_CLI_BLKID" ||
    return $?
  bl64_dbg_app_trace_start
  "$SYSOP64_LINUX_PATH_CLI_BLKID" \
    "$@"
  bl64_dbg_app_trace_stop
}

function linux_lib_run_cryptsetup() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$SYSOP64_LINUX_PATH_CLI_CRYPTSETUP" ||
    return $?
  bl64_dbg_app_trace_start
  "$SYSOP64_LINUX_PATH_CLI_CRYPTSETUP" \
    --verbose \
    "$@"
  bl64_dbg_app_trace_stop
}

function linux_lib_run_lsblk() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$SYSOP64_LINUX_PATH_CLI_LSBLK" ||
    return $?
  bl64_dbg_app_trace_start
  "$SYSOP64_LINUX_PATH_CLI_LSBLK" \
    "$@"
  bl64_dbg_app_trace_stop
}

function linux_lib_run_mount() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$SYSOP64_LINUX_PATH_CLI_MOUNT" ||
    return $?
  bl64_dbg_app_trace_start
  "$SYSOP64_LINUX_PATH_CLI_MOUNT" \
    --verbose \
    "$@"
  bl64_dbg_app_trace_stop
}

function linux_lib_run_fsck() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$SYSOP64_LINUX_PATH_CLI_FSCK" ||
    return $?
  bl64_dbg_app_trace_start
  "$SYSOP64_LINUX_PATH_CLI_FSCK" \
    -V \
    "$@"
  bl64_dbg_app_trace_stop
}

function linux_lib_run_badblocks() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$SYSOP64_LINUX_PATH_CLI_BADBLOCKS" ||
    return $?
  bl64_dbg_app_trace_start
  "$SYSOP64_LINUX_PATH_CLI_BADBLOCKS" \
    -v \
    "$@"
  bl64_dbg_app_trace_stop
}

function linux_lib_run_journalctl() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$SYSOP64_LINUX_PATH_CLI_JOURNALCTL" ||
    return $?
  bl64_dbg_app_trace_start
  "$SYSOP64_LINUX_PATH_CLI_JOURNALCTL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function linux_lib_run_mdadm() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$SYSOP64_LINUX_PATH_CLI_MDADM" ||
    return $?
  bl64_dbg_app_trace_start
  "$SYSOP64_LINUX_PATH_CLI_MDADM" \
    --verbose \
    "$@"
  bl64_dbg_app_trace_stop
}
