#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/lib/core.lib" && source "${S64_CORE_PATH_LIB}/sonobuoy.lib" && source "${S64_CORE_PATH_LIB}/k8s.lib" || { s64_core_lib_module_check && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64 && exit 1; }

function my_initialize() {
  bl64_dbg_app_show_function
  s64_sonobuoy_lib_setup &&
    s64_k8s_lib_setup_secondary &&
    bl64_check_export 'S64_SONOBUOY_PATH_E2E_REPO_CONFIG' &&
    bl64_check_export 'S64_SONOBUOY_IMAGE_SONOBUOY' &&
    bl64_check_export 'S64_SONOBUOY_IMAGE_KUBE_CONFORMANCE' &&
    bl64_check_export 'S64_SONOBUOY_IMAGE_SYSTEMD_LOGS'
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_set_about 'Start e2e conformance test. Mode: quick'
s64_core_lib_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
# shellcheck disable=SC2046
s64_sonobuoy_lib_run_sonobuoy \
  $(s64_k8s_lib_cli_set_kubeconfig) \
  run \
  --mode quick \
  --e2e-repo-config "$S64_SONOBUOY_PATH_E2E_REPO_CONFIG" \
  --sonobuoy-image "$S64_SONOBUOY_IMAGE_SONOBUOY" \
  --systemd-logs-image "$S64_SONOBUOY_IMAGE_SYSTEMD_LOGS" \
  --kube-conformance-image "$S64_SONOBUOY_IMAGE_KUBE_CONFORMANCE"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
