#!/usr/bin/env bash
# template: 1.0.0
# template-import: 1.0.0
#######################################
# Linux / LVM / VG / List
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
  { echo "Error: unable to load bashlib64" && exit 1; }
# shellcheck source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }

#
# Functions
#

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_privilege_root &&
    s64_linux_lib_setup
}

#
# Main
#

declare command='list'
declare fields='vg_name,vg_uuid,vg_fmt,vg_attr,vg_extent_size,vg_extent_count,vg_free_count,max_lv,max_pv'

bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" || exit $?
initialize || exit $?

bl64_msg_show_batch_start "$command"
s64_linux_lib_run_vgs \
  --nosuffix \
  --units M \
  --options "$fields"
bl64_msg_show_batch_finish $? "$command"
