#!/usr/bin/env bash
# template: 1.0.0
# template-import: 1.0.0
#######################################
# Linux / LVM / LV / List
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions andsrc/linux-lvm/linux-lvm-vg-list
# limitations under the License.
#######################################

#
# Imports
#

declare SYSOP64_CORE_PATH_ROOT="${SYSOP64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck source-path=SCRIPTDIR/..
source "${SYSOP64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck source-path=SCRIPTDIR/../../lib/bl64
source "${SYSOP64_CORE_PATH_BL64}/bashlib64-core.bash" ||
  { echo "Error: unable to load bashlib64" && exit 1; }
# shellcheck source-path=SCRIPT_PATH/..
source "${SYSOP64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }

#
# Functions
#

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_privilege_root &&
    linux_lib_setup
}

#
# Main
#

declare command='list'
declare debug="$BL64_DBG_TARGET_NONE"
declare verbose="$BL64_MSG_VERBOSE_ALL"
declare fields='lv_name,vg_name,lv_uuid,lv_attr,lv_size,seg_count,segtype,stripes,stripesize,chunksize'

bl64_dbg_set_level "$debug" && bl64_msg_set_level "$verbose" || exit $?
initialize || exit $?

bl64_msg_show_batch_start "$command"
linux_lib_run_lvs \
  --nosuffix \
  --units M \
  --options "$fields"
bl64_msg_show_batch_finish $? "$command"
