#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/linux.lib" || { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

declare MY_FILTER="${1:-}"

function my_list() {
  bl64_dbg_app_show_function "$@"
  local filter="${1:-}"

  case "$BL64_OS_FLAVOR" in
    "$BL64_OS_FLAVOR_ARCH")
      if [[ -n "$filter" ]]; then
        bl64_pkg_run_pacman --query --quiet --search "$filter"
      else
        bl64_pkg_run_pacman --query --quiet
      fi
      ;;
    "$BL64_OS_FLAVOR_DEBIAN")
      if [[ -n "$filter" ]]; then
        bl64_pkg_run_apt 'list' --installed |
          bl64_txt_run_grep "$filter"
      else
        bl64_pkg_run_apt 'list' --installed
      fi
      ;;
    "$BL64_OS_FLAVOR_FEDORA")
      if [[ -n "$filter" ]]; then
        bl64_pkg_run_dnf 'list' --installed |
          bl64_txt_run_grep "$filter"
      else
        bl64_pkg_run_dnf 'list' --installed
      fi
      ;;
    "$BL64_OS_FLAVOR_ALPINE")
      if [[ -n "$filter" ]]; then
        bl64_pkg_run_apk 'list' --installed |
          bl64_txt_run_grep "$filter"
      else
        bl64_pkg_run_apk 'list' --installed
      fi
      ;;
    "$BL64_OS_FLAVOR_REDHAT")
      if [[ "$BL64_OS_DISTRO" =~ ${BL64_OS_CNT}-7.* || "$BL64_OS_DISTRO" =~ ${BL64_OS_OL}-7.* ]]; then
        if [[ -n "$filter" ]]; then
          bl64_pkg_run_yum 'list' installed |
            bl64_txt_run_grep "$filter"
        else
          bl64_pkg_run_yum 'list' installed
        fi
      else
        if [[ -n "$filter" ]]; then
          bl64_pkg_run_dnf 'list' --installed |
            bl64_txt_run_grep "$filter"
        else
          bl64_pkg_run_dnf 'list' --installed
        fi
      fi
      ;;
    *) bl64_check_alert_unsupported || return $? ;;
  esac
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_linux_lib_setup &&
    bl64_check_privilege_root &&
    bl64_msg_show_setup "$S64_CORE_LABEL_TASK_PARAMETERS" \
      'MY_FILTER'
}

bl64_lib_script_version_set '1.2.0'
bl64_msg_help_about_set 'List installed operating system packages'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_list "$MY_FILTER"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
