#!/usr/bin/env bash
# template: 1.0.0
#######################################
# Core / Lib
#
# Version: 1.2.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

# shellcheck disable=SC2034
{
    # Default SysOp64 install path
    declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
    # Default BL64 install path
    declare S64_CORE_PATH_BL64="${S64_CORE_PATH_BL64:-/opt/bl64}"

    # Default debut level
    declare S64_CORE_SET_DEBUG="${S64_CORE_SET_DEBUG:-NONE}"
    # Default verbose level
    declare S64_CORE_SET_VERBOSE="${S64_CORE_SET_VERBOSE:-ALL}"

    # Default JQuery tool path
    declare S64_CORE_PATH_JQ="${S64_CORE_PATH_JQ:-/usr/bin/jq}"
}
