#!/usr/bin/env bash
# template-module-lib: 2.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_CORE_VERSION='2.0.1'

  # Default Automation64 install path
  declare S64_CORE_PATH_AT64="${HOME}/at64"
  [[ ! -d "$S64_CORE_PATH_AT64" ]] && S64_CORE_PATH_AT64='/opt'

  # Default SysOp64 install path
  declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-${S64_CORE_PATH_AT64}/sysop64}"

  # Default BL64 install path
  declare S64_CORE_PATH_BL64="${S64_CORE_PATH_BL64:-${S64_CORE_PATH_AT64}/bl64}"

  # Default log repository
  declare S64_CORE_PATH_LOGS="${S64_CORE_PATH_LOGS:-${HOME}/logs-sysop64}"

  # Default debut level
  declare S64_CORE_SET_DEBUG="${S64_CORE_SET_DEBUG:-NONE}"

  # Default verbose level
  declare S64_CORE_SET_VERBOSE="${S64_CORE_SET_VERBOSE:-ALL}"
}

#
# Functions
#

function s64_core_lib_setup_logging() {
  :
}
