#!/usr/bin/env bash
# template-module-lib: 2.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#
0
# shellcheck disable=SC2034
{
  declare S64_HELM_VERSION='1.0.0'
  declare S64_HELM_PATH_CLI="${S64_HELM_PATH_CLI:-}"
  declare S64_HELM_OUTPUT_FORMAT="${S64_HELM_OUTPUT_FORMAT:-table}"
}

#
# Functions
#

function s64_helm_lib_setup() {
  bl64_dbg_app_show_function
  s64_core_lib_command_assign 'S64_HELM_PATH_CLI' 'helm'
  bl64_msg_show_setup 'module parameters' \
    'S64_HELM_OUTPUT_FORMAT'
}

function s64_helm_lib_run_helm() {
  bl64_dbg_app_show_function "$@"
  s64_helm_lib_harden
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_HELM_PATH_CLI" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_helm_lib_harden() { 
  bl64_dbg_app_show_function
  bl64_dbg_lib_trace_start
  unset HELM_CACHE_HOME
  unset HELM_CONFIG_HOME
  unset HELM_DATA_HOME
  unset HELM_DEBUG
  unset HELM_DRIVER
  unset HELM_DRIVER_SQL_CONNECTION_STRING
  unset HELM_MAX_HISTORY
  unset HELM_NAMESPACE
  unset HELM_NO_PLUGINS
  unset HELM_PLUGINS
  unset HELM_REGISTRY_CONFIG
  unset HELM_REPOSITORY_CACHE
  unset HELM_REPOSITORY_CONFIG
  unset HELM_KUBEAPISERVER
  unset HELM_KUBECAFILE
  unset HELM_KUBEASGROUPS
  unset HELM_KUBEASUSER
  unset HELM_KUBECONTEXT
  unset HELM_KUBETOKEN
  unset HELM_KUBEINSECURE_SKIP_TLS_VERIFY
  unset HELM_KUBETLS_SERVER_NAME
  unset HELM_BURST_LIMIT
  unset HELM_QPS
  bl64_dbg_lib_trace_stop
}
