#!/usr/bin/env bash
# template-module-lib: 2.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-k8s.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_KIND_VERSION='2.0.4'
  declare S64_KIND_PATH_CLI="${S64_KIND_PATH_CLI:-}"

  # Cluster definition
  S64_KIND_PATH_CLUSTER_CONFIG="${S64_KIND_PATH_CLUSTER_CONFIG:-}"
  S64_KIND_SET_CLUSTER_NAME="${S64_KIND_SET_CLUSTER_NAME:-default}"
}

#
# Functions
#

function s64_kind_lib_setup() {
  bl64_dbg_app_show_function
  # shellcheck disable=SC2119
  bl64_cnt_setup &&
    bl64_k8s_setup ||
    return $?

  if [[ -z "$S64_KIND_PATH_CLI" ]]; then
    S64_KIND_PATH_CLI="$(bl64_bsh_command_locate 'kind')"
  fi
  return 0
}

function s64_kind_lib_run_kind() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbosity 1'
  bl64_check_command "$S64_KIND_PATH_CLI" "$BL64_VAR_DEFAULT" 'S64_KIND_PATH_CLI' || return $?
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_KIND_PATH_CLI" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}
