#!/usr/bin/env bash
# template-module-lib: 2.0.0
#######################################
# Linux / Lib
#
# Version: 2.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-cryp.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_LINUX_PATH_CLI_BADBLOCKS=''
  declare S64_LINUX_PATH_CLI_BLKID=''
  declare S64_LINUX_PATH_CLI_CRYPTSETUP=''
  declare S64_LINUX_PATH_CLI_FSCK=''
  declare S64_LINUX_PATH_CLI_JOURNALCTL=''
  declare S64_LINUX_PATH_CLI_LSBLK=''
  declare S64_LINUX_PATH_CLI_LVS=''
  declare S64_LINUX_PATH_CLI_MDADM=''
  declare S64_LINUX_PATH_CLI_MKFS=''
  declare S64_LINUX_PATH_CLI_MOUNT=''
  declare S64_LINUX_PATH_CLI_PVS=''
  declare S64_LINUX_PATH_CLI_VGS=''
}

#
# Functions
#

function s64_linux_lib_setup() {
  bl64_dbg_app_show_function
  # shellcheck disable=SC2154
  case "$BL64_OS_FLAVOR" in
  "$BL64_OS_FLAVOR_DEBIAN")
    S64_LINUX_PATH_CLI_BADBLOCKS='/usr/sbin/badblocks'
    S64_LINUX_PATH_CLI_BLKID='/usr/sbin/blkid'
    S64_LINUX_PATH_CLI_CRYPTSETUP='/usr/sbin/cryptsetup'
    S64_LINUX_PATH_CLI_FSCK='/usr/sbin/fsck'
    S64_LINUX_PATH_CLI_JOURNALCTL='/usr/bin/journalctl'
    S64_LINUX_PATH_CLI_LSBLK='/bin/lsblk'
    S64_LINUX_PATH_CLI_LSUSB='/bin/lsusb'
    S64_LINUX_PATH_CLI_LVS='/usr/sbin/lvs'
    S64_LINUX_PATH_CLI_MDADM='/usr/sbin/mdadm'
    S64_LINUX_PATH_CLI_MKFS='/usr/sbin/mkfs'
    S64_LINUX_PATH_CLI_MOUNT='/bin/mount'
    S64_LINUX_PATH_CLI_PVS='/usr/sbin/pvs'
    S64_LINUX_PATH_CLI_VGS='/usr/sbin/vgs'
    ;;
  "$BL64_OS_FLAVOR_FEDORA")
    S64_LINUX_PATH_CLI_BADBLOCKS='/usr/sbin/badblocks'
    S64_LINUX_PATH_CLI_BLKID='/usr/sbin/blkid'
    S64_LINUX_PATH_CLI_CRYPTSETUP='/usr/sbin/cryptsetup'
    S64_LINUX_PATH_CLI_FSCK='/usr/sbin/fsck'
    S64_LINUX_PATH_CLI_JOURNALCTL='/usr/bin/journalctl'
    S64_LINUX_PATH_CLI_LSBLK='/usr/bin/lsblk'
    S64_LINUX_PATH_CLI_LSUSB='/usr/bin/lsusb'
    S64_LINUX_PATH_CLI_LVS='/usr/sbin/lvs'
    S64_LINUX_PATH_CLI_MDADM='/usr/sbin/mdadm'
    S64_LINUX_PATH_CLI_MKFS='/usr/sbin/mkfs'
    S64_LINUX_PATH_CLI_MOUNT='/usr/bin/mount'
    S64_LINUX_PATH_CLI_PVS='/usr/sbin/pvs'
    S64_LINUX_PATH_CLI_VGS='/usr/sbin/vgs'
    ;;
  *) bl64_check_alert_unsupported ;;
  esac
}

function s64_linux_lib_run_blkid() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_BLKID" ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_BLKID" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_cryptsetup() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_CRYPTSETUP" ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_CRYPTSETUP" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_lsblk() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_LSBLK" ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_LSBLK" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_mount() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_MOUNT" ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_MOUNT" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_fsck() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='-V'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_FSCK" ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_FSCK" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_badblocks() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='-v'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_BADBLOCKS" ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_BADBLOCKS" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_journalctl() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_JOURNALCTL" ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_JOURNALCTL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_mdadm() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_MDADM" ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_MDADM" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_vgs() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_VGS" ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_VGS" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_lvs() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_LVS" ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_LVS" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_pvs() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_PVS" ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_PVS" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_mkfs() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_MKFS" ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_MKFS" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_lsusb() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_LSUSB" ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_LSUSB" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}
