#!/usr/bin/env bash
# template-module-lib: 2.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-cryp.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-api.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-vcs.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-rxtx.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-pkg.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_LINUX_VERSION='3.0.1'

  declare S64_LINUX_PATH_CLI_BADBLOCKS=''
  declare S64_LINUX_PATH_CLI_BLKID=''
  declare S64_LINUX_PATH_CLI_CRYPTSETUP=''
  declare S64_LINUX_PATH_CLI_DMSETUP=''
  declare S64_LINUX_PATH_CLI_DPKG_QUERY=''
  declare S64_LINUX_PATH_CLI_FSCK=''
  declare S64_LINUX_PATH_CLI_GRUB2MKCONFIG=''
  declare S64_LINUX_PATH_CLI_IP=''
  declare S64_LINUX_PATH_CLI_JOURNALCTL=''
  declare S64_LINUX_PATH_CLI_LDD=''
  declare S64_LINUX_PATH_CLI_LSBLK=''
  declare S64_LINUX_PATH_CLI_LSPCI=''
  declare S64_LINUX_PATH_CLI_LSUSB=''
  declare S64_LINUX_PATH_CLI_LVS=''
  declare S64_LINUX_PATH_CLI_MDADM=''
  declare S64_LINUX_PATH_CLI_MKFS=''
  declare S64_LINUX_PATH_CLI_MOUNT=''
  declare S64_LINUX_PATH_CLI_PVS=''
  declare S64_LINUX_PATH_CLI_UDISKSCTL=''
  declare S64_LINUX_PATH_CLI_RCSERVICE=''
  declare S64_LINUX_PATH_CLI_SYSTEMCTL=''
  declare S64_LINUX_PATH_CLI_VGS=''

  declare S64_LINUX_PATH_CFG_GRUB_OPTIONS=''
  declare S64_LINUX_PATH_CFG_GRUB_CONFIG=''
}

#
# Functions
#

function s64_linux_lib_setup() {
  bl64_dbg_app_show_function
  # shellcheck disable=SC2154,SC2034
  case "$BL64_OS_FLAVOR" in
  "$BL64_OS_FLAVOR_DEBIAN")
    S64_LINUX_PATH_CLI_BADBLOCKS='/usr/sbin/badblocks'
    S64_LINUX_PATH_CLI_BLKID='/usr/sbin/blkid'
    S64_LINUX_PATH_CLI_CRYPTSETUP='/usr/sbin/cryptsetup'
    S64_LINUX_PATH_CLI_DMSETUP='/usr/sbin/dmsetup'
    S64_LINUX_PATH_CLI_DPKG_QUERY='/usr/bin/dpkg-query'
    S64_LINUX_PATH_CLI_FSCK='/usr/sbin/fsck'
    S64_LINUX_PATH_CLI_GRUB2MKCONFIG='/usr/bin/grub2-mkconfig'
    S64_LINUX_PATH_CLI_IP='/usr/sbin/ip'
    S64_LINUX_PATH_CLI_JOURNALCTL='/usr/bin/journalctl'
    S64_LINUX_PATH_CLI_LDD='/usr/bin/ldd'
    S64_LINUX_PATH_CLI_LSBLK='/bin/lsblk'
    S64_LINUX_PATH_CLI_LSPCI='/bin/lspci'
    S64_LINUX_PATH_CLI_LSUSB='/bin/lsusb'
    S64_LINUX_PATH_CLI_LVS='/usr/sbin/lvs'
    S64_LINUX_PATH_CLI_MDADM='/usr/sbin/mdadm'
    S64_LINUX_PATH_CLI_MKFS='/usr/sbin/mkfs'
    S64_LINUX_PATH_CLI_MOUNT='/bin/mount'
    S64_LINUX_PATH_CLI_PVS='/usr/sbin/pvs'
    S64_LINUX_PATH_CLI_UDISKSCTL='/usr/bin/udisksctl'
    S64_LINUX_PATH_CLI_RCSERVICE="$BL64_VAR_INCOMPATIBLE"
    S64_LINUX_PATH_CLI_SYSTEMCTL='/bin/systemctl'
    S64_LINUX_PATH_CLI_VGS='/usr/sbin/vgs'

    S64_LINUX_PATH_CFG_GRUB_CONFIG='/boot/grub/grub.cfg'
    S64_LINUX_PATH_CFG_GRUB_OPTIONS='/etc/default/grub'
    ;;
  "$BL64_OS_FLAVOR_FEDORA" | "$BL64_OS_FLAVOR_REDHAT")
    S64_LINUX_PATH_CLI_BADBLOCKS='/usr/sbin/badblocks'
    S64_LINUX_PATH_CLI_BLKID='/usr/sbin/blkid'
    S64_LINUX_PATH_CLI_CRYPTSETUP='/usr/sbin/cryptsetup'
    S64_LINUX_PATH_CLI_DMSETUP='/usr/sbin/dmsetup'
    S64_LINUX_PATH_CLI_FSCK='/usr/sbin/fsck'
    S64_LINUX_PATH_CLI_GRUB2MKCONFIG='/usr/bin/grub2-mkconfig'
    S64_LINUX_PATH_CLI_IP='/usr/sbin/ip'
    S64_LINUX_PATH_CLI_JOURNALCTL='/usr/bin/journalctl'
    S64_LINUX_PATH_CLI_LDD='/usr/bin/ldd'
    S64_LINUX_PATH_CLI_LSBLK='/usr/bin/lsblk'
    S64_LINUX_PATH_CLI_LSPCI='/usr/bin/lspci'
    S64_LINUX_PATH_CLI_LSUSB='/usr/bin/lsusb'
    S64_LINUX_PATH_CLI_LVS='/usr/sbin/lvs'
    S64_LINUX_PATH_CLI_MDADM='/usr/sbin/mdadm'
    S64_LINUX_PATH_CLI_MKFS='/usr/sbin/mkfs'
    S64_LINUX_PATH_CLI_MOUNT='/usr/bin/mount'
    S64_LINUX_PATH_CLI_PVS='/usr/sbin/pvs'
    S64_LINUX_PATH_CLI_UDISKSCTL='/usr/bin/udisksctl'
    S64_LINUX_PATH_CLI_RCSERVICE="$BL64_VAR_INCOMPATIBLE"
    S64_LINUX_PATH_CLI_SYSTEMCTL='/usr/bin/systemctl'
    S64_LINUX_PATH_CLI_VGS='/usr/sbin/vgs'

    S64_LINUX_PATH_CFG_GRUB_CONFIG='/etc/grub2.cfg'
    S64_LINUX_PATH_CFG_GRUB_OPTIONS='/etc/default/grub'
    ;;
  "$BL64_OS_FLAVOR_ALPINE")
    S64_LINUX_PATH_CLI_BADBLOCKS='/sbin/badblocks'
    S64_LINUX_PATH_CLI_BLKID='/sbin/blkid'
    S64_LINUX_PATH_CLI_CRYPTSETUP='/sbin/cryptsetup'
    S64_LINUX_PATH_CLI_DMSETUP='/sbin/dmsetup'
    S64_LINUX_PATH_CLI_FSCK='/sbin/fsck'
    S64_LINUX_PATH_CLI_GRUB2MKCONFIG='/usr/sbin/grub-mkconfig'
    S64_LINUX_PATH_CLI_IP='/sbin/ip'
    S64_LINUX_PATH_CLI_JOURNALCTL='/bin/journalctl'
    S64_LINUX_PATH_CLI_LDD='/usr/bin/ldd'
    S64_LINUX_PATH_CLI_LSBLK='/bin/lsblk'
    S64_LINUX_PATH_CLI_LSPCI='/usr/bin/lspci'
    S64_LINUX_PATH_CLI_LSUSB='/usr/bin/lsusb'
    S64_LINUX_PATH_CLI_LVS='/sbin/lvs'
    S64_LINUX_PATH_CLI_MDADM='/sbin/mdadm'
    S64_LINUX_PATH_CLI_MKFS='/sbin/mkfs'
    S64_LINUX_PATH_CLI_MOUNT='/bin/mount'
    S64_LINUX_PATH_CLI_PVS='/sbin/pvs'
    S64_LINUX_PATH_CLI_UDISKSCTL='/usr/bin/udisksctl'
    S64_LINUX_PATH_CLI_RCSERVICE='/etc/init.d/rc-service'
    S64_LINUX_PATH_CLI_SYSTEMCTL='/usr/bin/systemctl'
    S64_LINUX_PATH_CLI_VGS='/sbin/vgs'

    S64_LINUX_PATH_CFG_GRUB_CONFIG='/boot/grub/grub.cfg'
    S64_LINUX_PATH_CFG_GRUB_OPTIONS='/etc/default/grub'
    ;;
  "$BL64_OS_FLAVOR_SUSE")
    S64_LINUX_PATH_CLI_BADBLOCKS='/usr/sbin/badblocks'
    S64_LINUX_PATH_CLI_BLKID='/usr/sbin/blkid'
    S64_LINUX_PATH_CLI_CRYPTSETUP='/usr/sbin/cryptsetup'
    S64_LINUX_PATH_CLI_DMSETUP='/usr/sbin/dmsetup'
    S64_LINUX_PATH_CLI_FSCK='/usr/sbin/fsck'
    S64_LINUX_PATH_CLI_GRUB2MKCONFIG='/usr/sbin/grub2-mkconfig'
    S64_LINUX_PATH_CLI_IP='/usr/sbin/ip'
    S64_LINUX_PATH_CLI_JOURNALCTL='/usr/bin/journalctl'
    S64_LINUX_PATH_CLI_LDD='/usr/bin/ldd'
    S64_LINUX_PATH_CLI_LSBLK='/usr/bin/lsblk'
    S64_LINUX_PATH_CLI_LSPCI='/usr/bin/lspci'
    S64_LINUX_PATH_CLI_LSUSB='/usr/bin/lsusb'
    S64_LINUX_PATH_CLI_LVS='/usr/sbin/lvs'
    S64_LINUX_PATH_CLI_MDADM='/usr/sbin/mdadm'
    S64_LINUX_PATH_CLI_MKFS='/usr/sbin/mkfs'
    S64_LINUX_PATH_CLI_MOUNT='/usr/bin/mount'
    S64_LINUX_PATH_CLI_PVS='/usr/sbin/pvs'
    S64_LINUX_PATH_CLI_UDISKSCTL='/usr/bin/udisksctl'
    S64_LINUX_PATH_CLI_RCSERVICE="$BL64_VAR_INCOMPATIBLE"
    S64_LINUX_PATH_CLI_SYSTEMCTL='/usr/bin/systemctl'
    S64_LINUX_PATH_CLI_VGS='/usr/sbin/vgs'

    S64_LINUX_PATH_CFG_GRUB_CONFIG='/boot/grub2/grub.cfg'
    S64_LINUX_PATH_CFG_GRUB_OPTIONS='/etc/default/grub'
    ;;
  *)
    bl64_check_alert_unsupported
    return $?
    ;;
  esac
}

function s64_linux_lib_run_udisksctl() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_UDISKSCTL" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_UDISKSCTL' ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_UDISKSCTL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_blkid() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_BLKID" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_BLKID' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_BLKID" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_cryptsetup() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_CRYPTSETUP" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_CRYPTSETUP' ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_CRYPTSETUP" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_lsblk() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_LSBLK" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_LSBLK' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_LSBLK" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_mount() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_MOUNT" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_MOUNT' ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_MOUNT" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_fsck() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='-V'
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_FSCK" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_FSCK' ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_FSCK" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_badblocks() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='-v'
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_BADBLOCKS" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_BADBLOCKS' ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_BADBLOCKS" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_journalctl() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_JOURNALCTL" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_JOURNALCTL' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_JOURNALCTL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_mdadm() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_MDADM" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_MDADM' ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_MDADM" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_vgs() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_VGS" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_VGS' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_VGS" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_lvs() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_LVS" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_LVS' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_LVS" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_pvs() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_PVS" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_PVS' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_PVS" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_mkfs() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='-v'
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_MKFS" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_MKFS' ||
    return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_MKFS" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_dmsetup() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  local command="$1"

  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_check_command "$S64_LINUX_PATH_CLI_DMSETUP" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_DMSETUP' ||
    return $?
  shift

  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_DMSETUP" \
    "$command" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_lspci() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_LSPCI" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_LSPCI' ||
    return $?

  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_LSPCI" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_lsusb() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_LSUSB" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_LSUSB' ||
    return $?

  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_LSUSB" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_grub2_mkconfig() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_GRUB2MKCONFIG" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_GRUB2MKCONFIG' ||
    return $?

  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_LINUX_PATH_CLI_GRUB2MKCONFIG" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_ldd() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_LDD" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_LDD' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_LDD" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_ip() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_IP" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_IP' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_IP" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_systemctl() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_SYSTEMCTL" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_SYSTEMCTL' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_SYSTEMCTL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_rcservice() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_LINUX_PATH_CLI_RCSERVICE" "$BL64_VAR_DEFAULT" 'S64_LINUX_PATH_CLI_RCSERVICE' ||
    return $?
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_RCSERVICE" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_linux_lib_run_dpkg_query() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  "$S64_LINUX_PATH_CLI_DPKG_QUERY" \
    "$@"
  bl64_dbg_app_trace_stop
}
