#!/usr/bin/env bash
# template-module-lib: 2.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_MACOS_VERSION='1.3.0'
  declare S64_MACOS_PATH_CLI_CODESIGN=''
  declare S64_MACOS_PATH_CLI_DEFAULTS=''
  declare S64_MACOS_PATH_CLI_DSCACHEUTIL=''
  declare S64_MACOS_PATH_CLI_KILLALL=''
  declare S64_MACOS_PATH_CLI_LSOF=''
  declare S64_MACOS_PATH_CLI_OSASCRIPT=''
  declare S64_MACOS_PATH_CLI_PKGUTIL=''
  declare S64_MACOS_PATH_CLI_PLUTIL=''
  declare S64_MACOS_PATH_CLI_SYSADMINCTL=''
}

#
# Functions
#

function s64_macos_lib_setup() {
  bl64_dbg_app_show_function
  case "$BL64_OS_FLAVOR" in
  "$BL64_OS_FLAVOR_MACOS")
    S64_MACOS_PATH_CLI_CODESIGN='/usr/bin/codesign'
    S64_MACOS_PATH_CLI_DEFAULTS='/usr/bin/defaults'
    S64_MACOS_PATH_CLI_DSCACHEUTIL='/usr/bin/dscacheutil'
    S64_MACOS_PATH_CLI_KILLALL='/usr/bin/killall'
    S64_MACOS_PATH_CLI_LSOF='/usr/sbin/lsof'
    S64_MACOS_PATH_CLI_OSASCRIPT='/usr/bin/osascript'
    S64_MACOS_PATH_CLI_PKGUTIL='/usr/sbin/pkgutil'
    S64_MACOS_PATH_CLI_PLUTIL='/usr/bin/plutil'
    S64_MACOS_PATH_CLI_SYSADMINCTL='/usr/sbin/sysadminctl'
    ;;
  *) bl64_check_alert_unsupported ;;
  esac
}

function s64_macos_lib_run_lsof() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_MACOS_PATH_CLI_LSOF" "$BL64_VAR_DEFAULT" 'S64_MACOS_PATH_CLI_LSOF' || return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_LSOF" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_macos_lib_run_codesign() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_MACOS_PATH_CLI_CODESIGN" "$BL64_VAR_DEFAULT" 'S64_MACOS_PATH_CLI_CODESIGN' || return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_CODESIGN" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_macos_lib_run_pkgutil() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_PKGUTIL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_macos_lib_run_dscacheutil() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_MACOS_PATH_CLI_DSCACHEUTIL" "$BL64_VAR_DEFAULT" 'S64_MACOS_PATH_CLI_DSCACHEUTIL' || return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_DSCACHEUTIL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_macos_lib_run_sysadminctl() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_SYSADMINCTL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_macos_lib_run_defaults() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_DEFAULTS" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_macos_lib_run_osascript() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_MACOS_PATH_CLI_OSASCRIPT" "$BL64_VAR_DEFAULT" 'S64_MACOS_PATH_CLI_OSASCRIPT' || return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_OSASCRIPT" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_macos_lib_run_killall() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_KILLALL" \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_macos_lib_run_plutil() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_MACOS_PATH_CLI_PLUTIL" "$BL64_VAR_DEFAULT" 'S64_MACOS_PATH_CLI_PLUTIL' || return $?
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_MACOS_PATH_CLI_PLUTIL" \
    "$@"
  bl64_dbg_app_trace_stop
}
