#!/usr/bin/env bash
# template-module-lib: 2.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_OPENSSH_VERSION='2.1.0'
  declare S64_OPENSSH_PATH_SSH="${S64_OPENSSH_PATH_SSH:-}"
  declare S64_OPENSSH_PATH_SSH_ADD="${S64_OPENSSH_PATH_SSH_ADD:-}"
  declare S64_OPENSSH_PATH_SSH_KEYGEN="${S64_OPENSSH_PATH_SSH_KEYGEN:-}"
}

#
# Functions
#

function s64_openssh_lib_setup() {
  bl64_dbg_app_show_function
  [[ -z "$S64_OPENSSH_PATH_SSH" ]] && S64_OPENSSH_PATH_SSH="$(bl64_bsh_command_locate 'ssh')"
  [[ -z "$S64_OPENSSH_PATH_SSH_ADD" ]] && S64_OPENSSH_PATH_SSH_ADD="$(bl64_bsh_command_locate 'ssh-add')"
  [[ -z "$S64_OPENSSH_PATH_SSH_KEYGEN" ]] && S64_OPENSSH_PATH_SSH_KEYGEN="$(bl64_bsh_command_locate 'ssh-keygen')"
  return 0
}

function s64_openssh_lib_run_ssh_keygen() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='-v'
  bl64_check_command "$S64_OPENSSH_PATH_SSH_KEYGEN" "$BL64_VAR_DEFAULT" 'S64_OPENSSH_PATH_SSH_KEYGEN' || return $?
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_OPENSSH_PATH_SSH_KEYGEN" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_openssh_lib_run_ssh() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='-v'
  bl64_check_command "$S64_OPENSSH_PATH_SSH" "$BL64_VAR_DEFAULT" 'S64_OPENSSH_PATH_SSH' || return $?
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_OPENSSH_PATH_SSH" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}

function s64_openssh_lib_run_ssh_add() {
  bl64_dbg_app_show_function "$@"
  bl64_check_command "$S64_OPENSSH_PATH_SSH_ADD" "$BL64_VAR_DEFAULT" 'S64_OPENSSH_PATH_SSH_ADD' || return $?
  bl64_msg_app_verbose_is_enabled || verbose_flag=' '
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_OPENSSH_PATH_SSH_ADD" \
    "$@"
  bl64_dbg_app_trace_stop
}
