#!/usr/bin/env bash
# template-module-lib: 2.0.0
#######################################
# PGSQL / Lib
#
# Version: 2.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-fs.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-txt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-xsv.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-fmt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-cnt.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_PGSQL_SERVER_LAB_NAME="${S64_PGSQL_SERVER_LAB_NAME:-pgsql-lab}"
  declare S64_PGSQL_SERVER_LAB_PASSWORD="${S64_PGSQL_SERVER_LAB_PASSWORD:-Random-Password.${RANDOM}}"
  declare S64_PGSQL_PATH_CLI="${S64_PGSQL_PATH_CLI:-}"

  declare S64_PGSQL_SERVER_HOST="${S64_PGSQL_SERVER_HOST:-localhost}"
  declare S64_PGSQL_SERVER_USER="${S64_PGSQL_SERVER_USER:-postgres}"
  declare S64_PGSQL_SERVER_PORT="${S64_PGSQL_SERVER_PORT:-5432}"
  declare S64_PGSQL_SERVER_PASSWORD="${S64_PGSQL_SERVER_PASSWORD:-}"
  declare S64_PGSQL_DB_NAME="${S64_PGSQL_DB_NAME:-postgres}"
}

function s64_psql_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$S64_PGSQL_PATH_CLI" ]]; then
    if [[ -x '/home/linuxbrew/.linuxbrew/bin/psql' ]]; then
      S64_PGSQL_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/psql'
    elif [[ -x '/opt/homebrew/bin/psql' ]]; then
      S64_PGSQL_PATH_CLI='/opt/homebrew/bin/psql'
    elif [[ -x '/usr/local/bin/psql' ]]; then
      S64_PGSQL_PATH_CLI='/usr/local/bin/psql'
    elif [[ -x '/usr/bin/psql' ]]; then
      S64_PGSQL_PATH_CLI='/usr/bin/psql'
    else
      bl64_check_alert_resource_not_found 'psql'
      return $?
    fi
  else
    bl64_check_command "$S64_PGSQL_PATH_CLI"
  fi
}

function s64_psql_lib_run_psql() {
  bl64_dbg_app_show_function "$@"
  "$S64_PGSQL_PATH_CLI" \
    "$@"
}
