#!/usr/bin/env bash
# template-module-lib: 2.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_RESTIC_VERSION='2.0.0'
  declare S64_RESTIC_PATH_CLI="${S64_RESTIC_PATH_CLI:-}"
  declare S64_RESTIC_PATH_REPOSITORY="${S64_RESTIC_PATH_REPOSITORY:-}"
  declare S64_RESTIC_PASSWORD="${S64_RESTIC_PASSWORD:-}"

  export RESTIC_REPOSITORY=''
  export RESTIC_PASSWORD=''
}

#
# Functions
#

function s64_restic_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$S64_RESTIC_PATH_CLI" ]]; then
    S64_RESTIC_PATH_CLI="$(bl64_bsh_command_locate 'restic')"
  else
    bl64_check_command "$S64_RESTIC_PATH_CLI" ||
      return $?
  fi
  bl64_check_privilege_root &&
    bl64_check_export 'S64_RESTIC_PATH_REPOSITORY' &&
    bl64_check_export 'S64_RESTIC_PASSWORD'
}

function s64_restic_lib_run_restic() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  RESTIC_REPOSITORY="$S64_RESTIC_PATH_REPOSITORY"
  RESTIC_PASSWORD="$S64_RESTIC_PASSWORD"
  bl64_msg_app_verbose_enabled || verbose_flag=' '

  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_RESTIC_PATH_CLI" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}
