#!/usr/bin/env bash
# template-module-lib: 2.0.0
#######################################
# RSync / Lib
#
# Version: 2.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-module-ui.bash" &&
  source "${S64_CORE_PATH_BL64}/bashlib64-module-bsh.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }

#
# Globals
#

# shellcheck disable=SC2034
{
  declare S64_RSYNC_PATH_CLI="${S64_RSYNC_PATH_CLI:-}"
  declare S64_RSYNC_OPTIONS_COMMON=''
  S64_RSYNC_OPTIONS_COMMON+=' --one-file-system'
  S64_RSYNC_OPTIONS_COMMON+=' --human-readable'
  S64_RSYNC_OPTIONS_COMMON+=' --progress'
  S64_RSYNC_OPTIONS_COMMON+=' --stats'
  S64_RSYNC_OPTIONS_COMMON+=' --recursive'
  S64_RSYNC_OPTIONS_COMMON+=' --checksum'
  S64_RSYNC_OPTIONS_COMMON+=' --links'
  S64_RSYNC_OPTIONS_COMMON+=' --delete'
  S64_RSYNC_OPTIONS_COMMON+=' --mkpath'
  S64_RSYNC_OPTIONS_COMMON+=' --verbose'
  S64_RSYNC_OPTIONS_COMMON+=' --perms'
  S64_RSYNC_OPTIONS_COMMON+=' --checksum'
  S64_RSYNC_OPTIONS_COMMON+=' --compress'
}

#
# Functions
#

function s64_rsync_lib_setup() {
  bl64_dbg_app_show_function
  if [[ -z "$S64_RSYNC_PATH_CLI" ]]; then
    if [[ -x '/home/linuxbrew/.linuxbrew/bin/rsync' ]]; then
      S64_RSYNC_PATH_CLI='/home/linuxbrew/.linuxbrew/bin/rsync'
    elif [[ -x '/opt/homebrew/bin/rsync' ]]; then
      S64_RSYNC_PATH_CLI='/opt/homebrew/bin/rsync'
    elif [[ -x '/usr/local/bin/rsync' ]]; then
      S64_RSYNC_PATH_CLI='/usr/local/bin/rsync'
    elif [[ -x '/usr/bin/rsync' ]]; then
      S64_RSYNC_PATH_CLI='/usr/bin/rsync'
    else
      bl64_check_alert_resource_not_found 'rsync'
      return $?
    fi
  else
    bl64_check_command "$S64_RSYNC_PATH_CLI" ||
      return $?
  fi
}

function s64_rsync_lib_run_rsync() {
  bl64_dbg_app_show_function "$@"
  local verbose_flag='--verbose'
  bl64_msg_app_verbose_enabled || verbose_flag=' '
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$S64_RSYNC_PATH_CLI" \
    $verbose_flag \
    "$@"
  bl64_dbg_app_trace_stop
}
