#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/openssh-lib" || { echo "Error: unable to load module library (S64_CORE_PATH_AT64=${S64_CORE_PATH_AT64})" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

function my_service_status_alpine() {
  bl64_dbg_app_show_function
  s64_linux_lib_run_rcservice sshd status
}

function my_service_status_debian() {
  bl64_dbg_app_show_function
  s64_linux_lib_run_systemctl status ssh
}

function my_service_status_fedora() {
  bl64_dbg_app_show_function
  s64_linux_lib_run_systemctl status sshd
}

function my_service_status_redhat() {
  bl64_dbg_app_show_function
  s64_linux_lib_run_systemctl status sshd
}

function my_service_status_suse() {
  bl64_dbg_app_show_function
  s64_linux_lib_run_systemctl status sshd
}

function my_service_status() {
  bl64_dbg_app_show_function
  case "$BL64_OS_FLAVOR" in
    "$BL64_OS_FLAVOR_ALPINE") my_service_status_alpine ;;
    "$BL64_OS_FLAVOR_DEBIAN") my_service_status_debian ;;
    "$BL64_OS_FLAVOR_FEDORA") my_service_status_fedora ;;
    "$BL64_OS_FLAVOR_REDHAT") my_service_status_redhat ;;
    "$BL64_OS_FLAVOR_SUSE") my_service_status_suse ;;
    *)
      bl64_check_alert_unsupported
      return $?
      ;;
  esac
}

function my_initialize() {
  bl64_dbg_app_show_function
  bl64_msg_show_about
  s64_openssh_lib_setup &&
    bl64_check_privilege_root &&
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_ALPINE" \
      "$BL64_OS_FLAVOR_DEBIAN" \
      "$BL64_OS_FLAVOR_FEDORA" \
      "$BL64_OS_FLAVOR_REDHAT" \
      "$BL64_OS_FLAVOR_SUSE"
}

bl64_lib_script_version_set '1.0.1'
bl64_msg_help_about_set 'Show SSH server status'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && my_initialize || exit $?
bl64_msg_show_batch_status "$BL64_SCRIPT_ID"
if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
  source "${S64_CORE_PATH_ROOT}/core/linux-lib" &&
    s64_linux_lib_setup
fi &&
  my_service_status
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
