#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/opentofu.lib" || { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

function my_initialize() {
  bl64_dbg_app_show_function
  s64_opentofu_lib_setup
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'Show CLI technical reference information'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_msg_show_doc 'Command Reference: https://opentofu.org/docs/cli/commands/'
bl64_msg_show_doc 'Environment Variables: https://opentofu.org/docs/cli/config/environment-variables/
  - TF_CLI_ARGS and TF_CLI_ARGS_name
  - TF_CLI_CONFIG_FILE
  - TF_DATA_DIR
  - TF_ENCRYPTION
  - TF_IGNORE
  - TF_IN_AUTOMATION
  - TF_INPUT
  - TF_LOG
  - TF_LOG_CORE 
  - TF_LOG_PATH
  - TF_LOG_PROVIDER 
  - TF_PLUGIN_CACHE_DIR
  - TF_PROVIDER_DOWNLOAD_RETRY
  - TF_REGISTRY_CLIENT_TIMEOUT
  - TF_REGISTRY_DISCOVERY_RETRY
  - TF_STATE_PERSIST_INTERVAL
  - TF_VAR_name
  - TF_WORKSPACE
  - TOFU_CPU_PROFILE'
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
