#!/usr/bin/env bash
# template-one: 3.0.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" && source "${S64_CORE_PATH_ROOT}/core/linux-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { echo 'Error: unable to load bashlib64' && exit 1; }

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_privilege_root &&
    bl64_check_parameter 'CIFS_SERVER_IP' &&
    bl64_check_parameter 'CIFS_SHARE_NAME' &&
    bl64_check_parameter 'MOUNT_PATH' &&
    bl64_check_directory "$MOUNT_PATH" &&
    s64_linux_lib_setup &&
    bl64_msg_show_setup 'Mount CIFS share' \
      'CIFS_SERVER_IP' \
      'CIFS_SHARE_NAME' \
      'MOUNT_PATH' \
      'CIFS_USER' \
      'CIFS_OPTIONS'
}

declare CIFS_SERVER_IP="${1:-}"
declare CIFS_SHARE_NAME="${2:-}"
declare MOUNT_PATH="${3:-}"
declare CIFS_USER="${4:-guest}"
declare CIFS_OPTIONS='nosetuids,cache=strict,mapchars'

bl64_lib_script_version_set '1.0.1'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" && initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
s64_linux_lib_run_mount \
  --type cifs \
  --options "${CIFS_OPTIONS},username=${CIFS_USER}" \
  "//${CIFS_SERVER_IP}/${CIFS_SHARE_NAME}" \
  "$MOUNT_PATH"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
