#!/usr/bin/env bash
# template: 1.0.0
#######################################
# Linux / Dev / Crypt / Mount
#
# Version: 1.0.0
#
#######################################
# Copyright [2024] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
# shellcheck source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core-lib" || { echo "Error: unable to load module library" && exit 1; }
# shellcheck disable=SC2015 source-path=SCRIPTDIR/../../lib/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" ||
  { echo 'Error: unable to load bashlib64' && exit 1; }
# shellcheck source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/linux/linux-lib" || { echo "Error: unable to load module library" && exit 1; }

#
# Functions
#

function luks_open() {
  bl64_dbg_app_show_function "$@"
  local device_path="${1:-}"
  local volume_name="${2:-}"
  bl64_msg_show_task "open luks device (${device_path} -> ${volume_name})"
  s64_linux_lib_run_cryptsetup \
    luksOpen \
    "$device_path" \
    "$volume_name"
}

function fs_check() {
  bl64_dbg_app_show_function "$@"
  local volume_name="${1:-}"
  bl64_msg_show_task "check filesystem (${volume_name})"
  s64_linux_lib_run_fsck \
    "/dev/mapper/${volume_name}"
}

function fs_mount() {
  bl64_dbg_app_show_function "$@"
  local mount_point="${1:-}"
  local volume_name="${2:-}"
  bl64_msg_show_task "mount filesystem (${volume_name} -> ${mount_point})"
  s64_linux_lib_run_mount \
    "/dev/mapper/${volume_name}" \
    "$mount_point"
}

function initialize() {
  bl64_dbg_app_show_function
  bl64_check_privilege_root &&
    bl64_check_parameter 'device_path' &&
    bl64_check_parameter 'mount_point' &&
    bl64_check_parameter 'volume_name' &&
    s64_linux_lib_setup
}

#
# Main
#

declare command='show'
declare device_path="${1:-}"
declare mount_point="${2:-}"
declare volume_name="${3:-}"

bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && bl64_msg_set_level "$S64_CORE_SET_VERBOSE" &&
  initialize || exit $?

bl64_msg_show_batch_start "$command"
luks_open "$device_path" "$volume_name" &&
  fs_check "$volume_name" &&
  fs_mount "$mount_point" "$volume_name"
bl64_msg_show_batch_finish $? "$command"
