#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
# shellcheck disable=SC2015 source-path=SCRIPTDIR/..
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/linux.lib" || { s64_core_lib_check_module_load && exit 1; }
# shellcheck disable=SC2015,SC2154 source-path=/opt/bl64
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

declare MY_DEVICE_PATH="${1:-}"
declare MY_MOUNT_POINT="${2:-}"
declare MY_VOLUME_NAME="${3:-}"

function luks_open() {
  bl64_dbg_app_show_function "$@"
  local device_path="${1:-}"
  local volume_name="${2:-}"
  bl64_msg_show_task "open luks device (${device_path} -> ${volume_name})"
  s64_linux_lib_run_cryptsetup \
    luksOpen \
    "$device_path" \
    "$volume_name"
}

function fs_check() {
  bl64_dbg_app_show_function "$@"
  local volume_name="${1:-}"
  bl64_msg_show_task "check filesystem (${volume_name})"
  s64_linux_lib_run_fsck \
    "/dev/mapper/${volume_name}"
}

function fs_mount() {
  bl64_dbg_app_show_function "$@"
  local mount_point="${1:-}"
  local volume_name="${2:-}"
  bl64_msg_show_task "mount filesystem (${volume_name} -> ${mount_point})"
  s64_linux_lib_run_mount \
    "/dev/mapper/${volume_name}" \
    "$mount_point"
}

function my_initialize() {
  bl64_dbg_app_show_function
  s64_core_lib_show_about
  s64_linux_lib_setup &&
    bl64_check_privilege_root &&
    bl64_check_parameter 'MY_DEVICE_PATH' &&
    bl64_check_parameter 'MY_MOUNT_POINT' &&
    bl64_check_parameter 'MY_VOLUME_NAME' &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'MY_DEVICE_PATH' \
      'MY_MOUNT_POINT' \
      'MY_VOLUME_LABEL'
}

bl64_lib_script_version_set '1.0.4'
bl64_msg_help_about_set 'Opens, checks and mount dm-crypt backed filesystem'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
luks_open "$MY_DEVICE_PATH" "$MY_VOLUME_NAME" &&
  fs_check "$MY_VOLUME_NAME" &&
  fs_mount "$MY_MOUNT_POINT" "$MY_VOLUME_NAME"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
