#!/usr/bin/env bash
# template-one: 3.2.1
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/linux.lib" || { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

function my_initialize() {
  bl64_dbg_app_show_function
  s64_core_lib_show_about
  s64_linux_lib_setup &&
    bl64_check_privilege_root
}

bl64_lib_script_version_set '1.0.2'
bl64_msg_help_about_set 'List DeviceMapper devices'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_msg_set_level "$BL64_MSG_VERBOSE_NONE"
s64_linux_lib_run_dmsetup \
  ls \
  --options 'device,blkdevname,active,open,rw,uuid' \
  --tree
bl64_msg_set_level "$S64_CORE_SET_VERBOSE"
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
