#!/usr/bin/env bash
# template-one: 3.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

declare S64_CORE_PATH_ROOT="${S64_CORE_PATH_ROOT:-/opt/sysop64}"
[[ ! -d "$S64_CORE_PATH_ROOT" ]] && S64_CORE_PATH_ROOT="${HOME}/at64/sysop64"
source "${S64_CORE_PATH_ROOT}/core/core.lib" && source "${S64_CORE_PATH_ROOT}/core/gcp.lib" || { s64_core_lib_check_module_load && exit 1; }
source "${S64_CORE_PATH_BL64}/bashlib64-core.bash" || { s64_core_lib_check_bl64_load && exit 1; }

function my_initialize() {
  bl64_dbg_app_show_function
  s64_gcp_lib_setup
}

bl64_lib_script_version_set '1.0.1'
bl64_msg_help_about_set 'Show technical reference information'
bl64_dbg_set_level "$S64_CORE_SET_DEBUG" && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
bl64_msg_show_doc 'Shell Environment Variables (https://docs.cloud.google.com/sdk/docs/properties#setting_properties_using_environment_variables):
  - CLOUDSDK_<SECTION_NAME>_<PROPERTY_NAME>=<VALUE>'
bl64_msg_show_doc 'Format Types (https://docs.cloud.google.com/sdk/gcloud/reference/topic/formats):
  - config: A dictionary of dictionaries in config style
  - csv: Comma Separated Values with no keys
  - default: An alias for the yaml format
  - diff: A unified diff of the first two projection columns
  - disable: Disables formatted output and does not consume the resources. Equivalent to the none format
  - flattened: A flattened tree. Each output line contains one key:value pair
  - get: Equivalent to the value[no-transforms] format
  - json
  - list: An ordered list of items
  - multi: Each projection key must have a subformat defined by the :format=FORMAT-STRING attribute
  - none: Disables formatted output and consumes the resources
  - object: Bypasses JSON-serialization and prints the object representation of each resource
  - table: Aligned left-adjusted columns with optional title, column headings and sorting
  - text: An alias for the flattened format
  - value: CSV with no heading and <TAB> separator instead of <COMMA>
  - yaml'
bl64_msg_show_doc 'Filters (https://docs.cloud.google.com/sdk/gcloud/reference/topic/filters):
  - NOT term-1
  - term-1 AND term-2
  - term-1 OR term-2
  - key : simple-pattern
  - key :( simple-pattern … )
  - key = value
  - key =( value … )
  - key != value
  - key < value
  - key <= value
  - key >= value
  - key > value
  - key ~ value
  - key !~ value'
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
